# Hesto Notebook (uv environment)
This notebook is configured to use the workspace Python environment managed by uv (.venv).

In [1]:
import sys
import pandas as pd
from pathlib import Path
from datetime import datetime
print(sys.executable)

c:\Users\shoffma5\Documents\GitHub_orig\hestodb\.venv\Scripts\python.exe

In [2]:
from hestodb.util import parse_file_path, find_latest_report_pptx
from hestodb.report import Report
from hestodb import _test_report_pptx
print(_test_report_pptx)

c:\Users\shoffma5\Documents\GitHub_orig\hestodb\hestodb\data\test\HESTO-202612_Report_24-HTIDS24_Smith-rev3.pptx

Checking the test file

In [3]:
test_report = Report(_test_report_pptx)
print(test_report)

Report HESTO-202612_Report_24-HTIDS24_Smith-rev3.pptx (33 slides)
Project ID: 24-HTIDS24-0009, PI: Jane Smith

Category    Prior    Current
----------  -------  -------
overall     Y        Y
cost        Y        Y
schedule    G        G
technical   G        G
staffing    G        G
facilities  G        G

Accommodation:
Category                          Sub-category  Value
--------------------------------  ----------  --------------
payload size                      length      10.0
                                  width       10.0
                                  height      10.0
payload volume                                1.0
power requirements                average     5.0
                                  peak        10.0
mass                                          5.4
pointing requirements             arcsecs     60.0
                                  arcminutes  1.0
data rate                         average     15.0
                                  peak        100.0
power interface port                          db-9, 28 v, 1a
communication interface protocol              uart
data communication port                       db-9
requires thermal isolation                    false
special power considerations                  none

Publications:
      Type choose one of below                                                   Title Publication/Presentation Date Publisher/Conference Name                                           URL
Conference presentation (oral) Development of the Next-Generation Solar X-ray detector                   23-Jan-2026              IEEE NSS/MIC https://ieeexplore.ieee.org/document/10657175

In [4]:
test_report.accomodation_table

                            category sub_category           value
0                       payload size       length            10.0
1                       payload size        width            10.0
2                       payload size       height            10.0
3                     payload volume                          1.0
4                 power requirements      average             5.0
5                 power requirements         peak            10.0
6                               mass                          5.4
7              pointing requirements      arcsecs            60.0
8              pointing requirements   arcminutes             1.0
9                          data rate      average            15.0
10                         data rate         peak           100.0
11              power interface port               db-9, 28 v, 1a
12  communication interface protocol                         uart
13           data communication port                         db-9
14        requires thermal isolation                        false
15      special power considerations                         none

In [5]:
test_report.publication_table

,Type choose one of below,Title,Publication/Presentation Date,Publisher/Conference Name,URL
0,Conference presentation (oral),Development of the Next-Generation Solar X-ray...,23-Jan-2026,IEEE NSS/MIC,https://ieeexplore.ieee.org/document/10657175

In [6]:
test_report.patents_table

,"Type (Issued, Filing)",Name,Patent or License Number,Date,"Resource Link (e.g., Google Patents Link)"
0,Issued,Art of transmitting electrical energy through ...,US787412A,1900-05-16,https://patents.google.com/patent/US787412A/

In [7]:
test_report.student_metrics_table

,Student Name (first last),Major,"Affiliation (School, University, etc.)","Level (High School, Undergrad, Grad, PhD)"
0,John Doe,Physics,University of Alabama,Undergrad

In [8]:
files = [
    find_latest_report_pptx(Path("C:\\Users\\shoffma5\\Box\\HESTO\\HTIDeS")),
    find_latest_report_pptx(Path("C:\\Users\\shoffma5\\Box\\HESTO\\HFOS")),
    find_latest_report_pptx(Path("C:\\Users\\shoffma5\\Box\\HESTO\\Special Projects"))
]
files = pd.concat(files, ignore_index=True)
reports = [Report(p) for p in files["file_path"]]
print(f"Found {len(reports)} report files:")
files.to_csv("report_files.csv", index=False)
files

HESTO-202601_TriannualReport_20-HTIDS20-0004_Sewell.pptx: unrecognised publication type 'Design Review'. Expected one of: ['Peer-reviewed publication', 'Non-Peer-reviewed publication', 'Conference presentation (oral)', 'Conference presentation (poster)', 'Web article']
HESTO-202601_TriannualReport_20-HTIDS20-0004_Sewell.pptx: unrecognised publication type 'Poster Presentation'. Expected one of: ['Peer-reviewed publication', 'Non-Peer-reviewed publication', 'Conference presentation (oral)', 'Conference presentation (poster)', 'Web article']
HESTO-202601_TriannualReport_20-HTIDS20-0004_Sewell.pptx: unrecognised publication type 'Design Review'. Expected one of: ['Peer-reviewed publication', 'Non-Peer-reviewed publication', 'Conference presentation (oral)', 'Conference presentation (poster)', 'Web article']
HESTO-202601_TriannualReport_20-HTIDS20-0004_Sewell.pptx: unrecognised publication type 'Oral Presentation'. Expected one of: ['Peer-reviewed publication', 'Non-Peer-reviewed publication', 'Conference presentation (oral)', 'Conference presentation (poster)', 'Web article']
HESTO-202601_TriannualReport_20-HTIDS20-00009_Cohen_v1.pptx: unrecognised publication type 'Poster'. Expected one of: ['Peer-reviewed publication', 'Non-Peer-reviewed publication', 'Conference presentation (oral)', 'Conference presentation (poster)', 'Web article']
HESTO-202601_TriannualReport_20-HTIDS20-00009_Cohen_v1.pptx: unrecognised publication type 'Talk'. Expected one of: ['Peer-reviewed publication', 'Non-Peer-reviewed publication', 'Conference presentation (oral)', 'Conference presentation (poster)', 'Web article']
HESTO-202601_TriannualReport_20-HTIDS20-00009_Cohen_v2.pptx: unrecognised publication type 'Poster'. Expected one of: ['Peer-reviewed publication', 'Non-Peer-reviewed publication', 'Conference presentation (oral)', 'Conference presentation (poster)', 'Web article']
HESTO-202601_TriannualReport_20-HTIDS20-00009_Cohen_v2.pptx: unrecognised publication type 'Talk'. Expected one of: ['Peer-reviewed publication', 'Non-Peer-reviewed publication', 'Conference presentation (oral)', 'Conference presentation (poster)', 'Web article']
HESTO-202605_TriannualReport_20-HTIDS20-00009_Cohen_v1.pptx: unrecognised publication type 'Poster'. Expected one of: ['Peer-reviewed publication', 'Non-Peer-reviewed publication', 'Conference presentation (oral)', 'Conference presentation (poster)', 'Web article']
HESTO-202605_TriannualReport_20-HTIDS20-00009_Cohen_v1.pptx: unrecognised publication type 'Talk'. Expected one of: ['Peer-reviewed publication', 'Non-Peer-reviewed publication', 'Conference presentation (oral)', 'Conference presentation (poster)', 'Web article']
HESTO-202601_TriannualReport_20-HTIDS20-0010_BONNELL-20260219-rev2.pptx: unrecognised publication type 'Oral'. Expected one of: ['Peer-reviewed publication', 'Non-Peer-reviewed publication', 'Conference presentation (oral)', 'Conference presentation (poster)', 'Web article']
HESTO-202601_TriannualReport_20-HTIDS20-0010_BONNELL-20260219-rev2.pptx: unrecognised publication type 'Oral'. Expected one of: ['Peer-reviewed publication', 'Non-Peer-reviewed publication', 'Conference presentation (oral)', 'Conference presentation (poster)', 'Web article']
HESTO-202601_TriannualReport_20-HTIDS20-0010_BONNELL-20260219-rev2.pptx: unrecognised publication type 'Oral/Poster'. Expected one of: ['Peer-reviewed publication', 'Non-Peer-reviewed publication', 'Conference presentation (oral)', 'Conference presentation (poster)', 'Web article']
HESTO-202601_TriannualReport_20-HTIDS20-0010_BONNELL-20260219-rev2.pptx: unrecognised publication type 'Oral'. Expected one of: ['Peer-reviewed publication', 'Non-Peer-reviewed publication', 'Conference presentation (oral)', 'Conference presentation (poster)', 'Web article']
HESTO-202601_TriannualReport_20-HTIDS20-0010_BONNELL-20260219-rev2.pptx: unrecognised publication type 'Oral'. Expected one of: ['Peer-reviewed publication', 'Non-Peer-reviewed publication', 'Conference presentation (oral)', 'Conference presentation (poster)', 'Web article']
HESTO-202601_TriannualReport_20-HTIDS20-0010_BONNELL-20260219-rev2.pptx: unrecognised publication type 'Oral'. Expected one of: ['Peer-reviewed publication', 'Non-Peer-reviewed publication', 'Conference presentation (oral)', 'Conference presentation (poster)', 'Web article']
HESTO-202601_TriannualReport_20-HTIDS20-0010_BONNELL-20260219-rev2.pptx: unrecognised publication type 'Oral'. Expected one of: ['Peer-reviewed publication', 'Non-Peer-reviewed publication', 'Conference presentation (oral)', 'Conference presentation (poster)', 'Web article']
HESTO-202601_TriannualReport_20-HTIDS20-0010_BONNELL-20260219-rev2.pptx: unrecognised publication type 'Oral'. Expected one of: ['Peer-reviewed publication', 'Non-Peer-reviewed publication', 'Conference presentation (oral)', 'Conference presentation (poster)', 'Web article']
HESTO-202601_TriannualReport_20-HTIDS20-0010_BONNELL-20260219-rev2.pptx: unrecognised publication type 'Oral'. Expected one of: ['Peer-reviewed publication', 'Non-Peer-reviewed publication', 'Conference presentation (oral)', 'Conference presentation (poster)', 'Web article']
HESTO-202601_TriannualReport_20-HTIDS20-0010_BONNELL-20260219-rev2.pptx: unrecognised publication type 'Poster'. Expected one of: ['Peer-reviewed publication', 'Non-Peer-reviewed publication', 'Conference presentation (oral)', 'Conference presentation (poster)', 'Web article']
HESTO-202601_TriannualReport_20-HTIDS20-0010_BONNELL-20260219-rev2.pptx: unrecognised publication type 'Oral'. Expected one of: ['Peer-reviewed publication', 'Non-Peer-reviewed publication', 'Conference presentation (oral)', 'Conference presentation (poster)', 'Web article']
HESTO-202604_TriannualReport_20-HTIDS20-0010_BONNELL-rev3.pptx: unrecognised publication type 'Peer-reviewed journal'. Expected one of: ['Peer-reviewed publication', 'Non-Peer-reviewed publication', 'Conference presentation (oral)', 'Conference presentation (poster)', 'Web article']
HESTO-202604_TriannualReport_20-HTIDS20-0010_BONNELL-rev3.pptx: unrecognised publication type 'Non-peer-reviewed journal'. Expected one of: ['Peer-reviewed publication', 'Non-Peer-reviewed publication', 'Conference presentation (oral)', 'Conference presentation (poster)', 'Web article']
HESTO-202602_TriannualReport_20-HTIDS20-0031_PIMouikis.pptx: unrecognised publication type 'Conference'. Expected one of: ['Peer-reviewed publication', 'Non-Peer-reviewed publication', 'Conference presentation (oral)', 'Conference presentation (poster)', 'Web article']
HESTO-202602_TriannualReport_20-HTIDS20-0031_PIMouikis.pptx: unrecognised publication type 'Conference'. Expected one of: ['Peer-reviewed publication', 'Non-Peer-reviewed publication', 'Conference presentation (oral)', 'Conference presentation (poster)', 'Web article']
HESTO-202602_TriannualReport_20-HTIDS20-0031_PIMouikis.pptx: unrecognised publication type 'Conference'. Expected one of: ['Peer-reviewed publication', 'Non-Peer-reviewed publication', 'Conference presentation (oral)', 'Conference presentation (poster)', 'Web article']
HESTO-202602_TriannualReport_20-HTIDS20-0031_PIMouikis.pptx: unrecognised publication type 'Conference'. Expected one of: ['Peer-reviewed publication', 'Non-Peer-reviewed publication', 'Conference presentation (oral)', 'Conference presentation (poster)', 'Web article']
HESTO-202602_TriannualReport_20-HTIDS20-0031_PIMouikis.pptx: unrecognised publication type 'Conference'. Expected one of: ['Peer-reviewed publication', 'Non-Peer-reviewed publication', 'Conference presentation (oral)', 'Conference presentation (poster)', 'Web article']
HESTO-202602_TriannualReport_20-HTIDS20-0031_PIMouikis.pptx: unrecognised publication type 'Publication'. Expected one of: ['Peer-reviewed publication', 'Non-Peer-reviewed publication', 'Conference presentation (oral)', 'Conference presentation (poster)', 'Web article']
HESTO-202602_TriannualReport_20-HTIDS20-0031_PIMouikis.pptx: unrecognised publication type 'Publication'. Expected one of: ['Peer-reviewed publication', 'Non-Peer-reviewed publication', 'Conference presentation (oral)', 'Conference presentation (poster)', 'Web article']
HESTO-202601_TriannualReport_20-HTIDS20-0034_Zhao.pptx: unrecognised publication type 'Presentation'. Expected one of: ['Peer-reviewed publication', 'Non-Peer-reviewed publication', 'Conference presentation (oral)', 'Conference presentation (poster)', 'Web article']
HESTO-202601_TriannualReport_20-HTIDS20-0034_Zhao.pptx: unrecognised publication type 'Presentation'. Expected one of: ['Peer-reviewed publication', 'Non-Peer-reviewed publication', 'Conference presentation (oral)', 'Conference presentation (poster)', 'Web article']
HESTO-202601_TriannualReport_20-HTIDS20-0034_Zhao.pptx: unrecognised publication type 'Presentation'. Expected one of: ['Peer-reviewed publication', 'Non-Peer-reviewed publication', 'Conference presentation (oral)', 'Conference presentation (poster)', 'Web article']
HESTO-202601_TriannualReport_20-HTIDS20-0034_Zhao.pptx: unrecognised publication type 'Presentation'. Expected one of: ['Peer-reviewed publication', 'Non-Peer-reviewed publication', 'Conference presentation (oral)', 'Conference presentation (poster)', 'Web article']
HESTO-202601_TriannualReport_20-HTIDS20-0034_Zhao.pptx: unrecognised publication type 'Presentation'. Expected one of: ['Peer-reviewed publication', 'Non-Peer-reviewed publication', 'Conference presentation (oral)', 'Conference presentation (poster)', 'Web article']
HESTO-202601_TriannualReport_20-HTIDS20-0034_Zhao.pptx: unrecognised publication type 'Presentation'. Expected one of: ['Peer-reviewed publication', 'Non-Peer-reviewed publication', 'Conference presentation (oral)', 'Conference presentation (poster)', 'Web article']
HESTO-202601_TriannualReport_20-HTIDS20-0034_Zhao.pptx: unrecognised publication type 'Presentation'. Expected one of: ['Peer-reviewed publication', 'Non-Peer-reviewed publication', 'Conference presentation (oral)', 'Conference presentation (poster)', 'Web article']
HESTO-202601_TriannualReport_20-HTIDS20-0034_Zhao.pptx: unrecognised publication type 'Publication'. Expected one of: ['Peer-reviewed publication', 'Non-Peer-reviewed publication', 'Conference presentation (oral)', 'Conference presentation (poster)', 'Web article']
HESTO-202601_TriannualReport_20-HTIDS20-0034_Zhao.pptx: unrecognised publication type 'Presentation'. Expected one of: ['Peer-reviewed publication', 'Non-Peer-reviewed publication', 'Conference presentation (oral)', 'Conference presentation (poster)', 'Web article']
HESTO-202601_TriannualReport_20-HTIDS20-0034_Zhao.pptx: unrecognised publication type 'Presentation'. Expected one of: ['Peer-reviewed publication', 'Non-Peer-reviewed publication', 'Conference presentation (oral)', 'Conference presentation (poster)', 'Web article']
HESTO-202601_TriannualReport_20-HTIDS20-0034_Zhao.pptx: unrecognised publication type 'Presentation'. Expected one of: ['Peer-reviewed publication', 'Non-Peer-reviewed publication', 'Conference presentation (oral)', 'Conference presentation (poster)', 'Web article']
HESTO-202601_TriannualReport_20-HTIDS20-0034_Zhao.pptx: unrecognised publication type 'Presentation'. Expected one of: ['Peer-reviewed publication', 'Non-Peer-reviewed publication', 'Conference presentation (oral)', 'Conference presentation (poster)', 'Web article']
HESTO-202601_TriannualReport_20-HTIDS20-0034_Zhao.pptx: unrecognised publication type 'Presentation'. Expected one of: ['Peer-reviewed publication', 'Non-Peer-reviewed publication', 'Conference presentation (oral)', 'Conference presentation (poster)', 'Web article']
HESTO-202601_TriannualReport_20-HTIDS20-0034_Zhao.pptx: unrecognised publication type 'Presentation and publication'. Expected one of: ['Peer-reviewed publication', 'Non-Peer-reviewed publication', 'Conference presentation (oral)', 'Conference presentation (poster)', 'Web article']
HESTO-202601_TriannualReport_20-HTIDS20-0034_Zhao.pptx: unrecognised publication type 'Presentation'. Expected one of: ['Peer-reviewed publication', 'Non-Peer-reviewed publication', 'Conference presentation (oral)', 'Conference presentation (poster)', 'Web article']
HESTO-202601_TriannualReport_20-HTIDS20-0034_Zhao.pptx: unrecognised publication type 'Presentation'. Expected one of: ['Peer-reviewed publication', 'Non-Peer-reviewed publication', 'Conference presentation (oral)', 'Conference presentation (poster)', 'Web article']
HESTO-202601_TriannualReport_20-HTIDS20-0034_Zhao.pptx: unrecognised publication type 'Presentation'. Expected one of: ['Peer-reviewed publication', 'Non-Peer-reviewed publication', 'Conference presentation (oral)', 'Conference presentation (poster)', 'Web article']
HESTO-202601_TriannualReport_20-HTIDS20-0034_Zhao.pptx: unrecognised publication type 'Presentation'. Expected one of: ['Peer-reviewed publication', 'Non-Peer-reviewed publication', 'Conference presentation (oral)', 'Conference presentation (poster)', 'Web article']
HESTO-202601_TriannualReport_20-HTIDS20-0034_Zhao.pptx: unrecognised publication type 'Presentation'. Expected one of: ['Peer-reviewed publication', 'Non-Peer-reviewed publication', 'Conference presentation (oral)', 'Conference presentation (poster)', 'Web article']
HESTO-202601_TriannualReport_20-HTIDS20-0034_Zhao.pptx: unrecognised publication type 'Presentation'. Expected one of: ['Peer-reviewed publication', 'Non-Peer-reviewed publication', 'Conference presentation (oral)', 'Conference presentation (poster)', 'Web article']
HESTO-202604_Report_20-HTIDS20-0034_Zhao.pptx: unrecognised publication type 'Peer-reviewed journal'. Expected one of: ['Peer-reviewed publication', 'Non-Peer-reviewed publication', 'Conference presentation (oral)', 'Conference presentation (poster)', 'Web article']
HESTO-202604_Report_20-HTIDS20-0034_Zhao.pptx: unrecognised publication type 'Non-peer-reviewed journal and Conference presentation (oral)'. Expected one of: ['Peer-reviewed publication', 'Non-Peer-reviewed publication', 'Conference presentation (oral)', 'Conference presentation (poster)', 'Web article']
HESTO-202601_TriannualReport_HTIDS21-0004_Zhang.pptx: unrecognised publication type 'Poster Presentation'. Expected one of: ['Peer-reviewed publication', 'Non-Peer-reviewed publication', 'Conference presentation (oral)', 'Conference presentation (poster)', 'Web article']
HESTO-202601_TriannualReport_HTIDS21-0004_Zhang.pptx: unrecognised publication type 'Oral Presentation'. Expected one of: ['Peer-reviewed publication', 'Non-Peer-reviewed publication', 'Conference presentation (oral)', 'Conference presentation (poster)', 'Web article']
HESTO-202604_Report_21-HTIDS21-0012_Clemmons.pptx: unrecognised publication type 'Peer-reviewed journal'. Expected one of: ['Peer-reviewed publication', 'Non-Peer-reviewed publication', 'Conference presentation (oral)', 'Conference presentation (poster)', 'Web article']
HESTO-202604_Report_21-HTIDS21-0012_Clemmons.pptx: unrecognised publication type 'Non-peer-reviewed journal'. Expected one of: ['Peer-reviewed publication', 'Non-Peer-reviewed publication', 'Conference presentation (oral)', 'Conference presentation (poster)', 'Web article']
HESTO-202604_Report_ProposalNumber_Nemark-rev3.pptx: unrecognised publication type 'Peer-reviewed journal'. Expected one of: ['Peer-reviewed publication', 'Non-Peer-reviewed publication', 'Conference presentation (oral)', 'Conference presentation (poster)', 'Web article']
HESTO-202604_Report_ProposalNumber_Nemark-rev3.pptx: unrecognised publication type 'Non-peer-reviewed journal'. Expected one of: ['Peer-reviewed publication', 'Non-Peer-reviewed publication', 'Conference presentation (oral)', 'Conference presentation (poster)', 'Web article']
HESTO-202604_Report_ProposalNumber_Newmark-rev3.pptx: unrecognised publication type 'Peer-reviewed journal'. Expected one of: ['Peer-reviewed publication', 'Non-Peer-reviewed publication', 'Conference presentation (oral)', 'Conference presentation (poster)', 'Web article']
HESTO-202604_Report_ProposalNumber_Newmark-rev3.pptx: unrecognised publication type 'Non-peer-reviewed journal'. Expected one of: ['Peer-reviewed publication', 'Non-Peer-reviewed publication', 'Conference presentation (oral)', 'Conference presentation (poster)', 'Web article']
HESTO-202605_Report_22-HTIDS22-0007_Mayyasi-rev3.pptx: unrecognised publication type 'Peer-reviewed journal'. Expected one of: ['Peer-reviewed publication', 'Non-Peer-reviewed publication', 'Conference presentation (oral)', 'Conference presentation (poster)', 'Web article']
HESTO-202605_Report_22-HTIDS22-0007_Mayyasi-rev3.pptx: unrecognised publication type 'Non-peer-reviewed journal'. Expected one of: ['Peer-reviewed publication', 'Non-Peer-reviewed publication', 'Conference presentation (oral)', 'Conference presentation (poster)', 'Web article']
HESTO-202601_TriannualReport_22-HTIDS22-0008_KALOGERAKIS-rev2.pptx: unrecognised publication type 'Oral Presentation'. Expected one of: ['Peer-reviewed publication', 'Non-Peer-reviewed publication', 'Conference presentation (oral)', 'Conference presentation (poster)', 'Web article']
HESTO-202601_TriannualReport_22-HTIDS22-0008_KALOGERAKIS-rev2.pptx: unrecognised publication type 'Conference Abstract'. Expected one of: ['Peer-reviewed publication', 'Non-Peer-reviewed publication', 'Conference presentation (oral)', 'Conference presentation (poster)', 'Web article']
HESTO-202601_TriannualReport_22-HTIDS22-0008_KALOGERAKIS-rev2.pptx: unrecognised publication type 'Conference Abstract'. Expected one of: ['Peer-reviewed publication', 'Non-Peer-reviewed publication', 'Conference presentation (oral)', 'Conference presentation (poster)', 'Web article']
HESTO-202601_TriannualReport_22-HTIDS22-0008_KALOGERAKIS-rev2.pptx: unrecognised publication type 'Conference Abstract'. Expected one of: ['Peer-reviewed publication', 'Non-Peer-reviewed publication', 'Conference presentation (oral)', 'Conference presentation (poster)', 'Web article']
HESTO-202601_TriannualReport_22-HTIDS22-0008_KALOGERAKIS-rev2.pptx: unrecognised publication type 'Peer-Reviewed Journal Article'. Expected one of: ['Peer-reviewed publication', 'Non-Peer-reviewed publication', 'Conference presentation (oral)', 'Conference presentation (poster)', 'Web article']
HESTO-202601_TriannualReport_22-HTIDS22-0008_KALOGERAKIS-rev2.pptx: unrecognised publication type 'Conference Abstract'. Expected one of: ['Peer-reviewed publication', 'Non-Peer-reviewed publication', 'Conference presentation (oral)', 'Conference presentation (poster)', 'Web article']
HESTO-202601_TriannualReport_22-HTIDS22-0008_KALOGERAKIS-rev2.pptx: unrecognised publication type 'Conference Abstract'. Expected one of: ['Peer-reviewed publication', 'Non-Peer-reviewed publication', 'Conference presentation (oral)', 'Conference presentation (poster)', 'Web article']
HESTO-202601_TriannualReport_22-HTIDS22-0008_KALOGERAKIS-rev2.pptx: unrecognised publication type 'Oral Presentation'. Expected one of: ['Peer-reviewed publication', 'Non-Peer-reviewed publication', 'Conference presentation (oral)', 'Conference presentation (poster)', 'Web article']
HESTO-202601_TriannualReport_22-HTIDS22-0008_KALOGERAKIS-rev2.pptx: unrecognised publication type 'Conference Abstract'. Expected one of: ['Peer-reviewed publication', 'Non-Peer-reviewed publication', 'Conference presentation (oral)', 'Conference presentation (poster)', 'Web article']
HESTO-202601_TriannualReport_22-HTIDS22-0008_KALOGERAKIS-rev2.pptx: unrecognised publication type 'Oral Presentation'. Expected one of: ['Peer-reviewed publication', 'Non-Peer-reviewed publication', 'Conference presentation (oral)', 'Conference presentation (poster)', 'Web article']

Found 24 report files:

,file_path,project_id,report_date,year,principal_investigator,affiliation,research_regime,modified,folder,is_active
0,C:\Users\shoffma5\Box\HESTO\HTIDeS\24-HTIDS\24...,24-HTIDS24-0022,2026-05-11,2024,Lindsay Glesener,University of Minnesota,"Solar Science, Heliosphere, Space Weather",2026-06-10 10:51:52,C:\Users\shoffma5\Box\HESTO\HTIDeS\24-HTIDS\24...,Yes
1,C:\Users\shoffma5\Box\HESTO\HTIDeS\24-HTIDS\24...,24-HTIDS24-0005,2026-04-15,2024,Georgia de Nolfo,NASA Goddard Space Flight Center,"Solar Science, Heliosphere, Space Weather",2026-04-26 13:47:32,C:\Users\shoffma5\Box\HESTO\HTIDeS\24-HTIDS\24...,Yes
2,C:\Users\shoffma5\Box\HESTO\HTIDeS\24-HTIDS\24...,24-HTIDS24-0006,2026-04-30,2024,Shawn Liang,Johns Hopkins University Applied Physics Labor...,"Magnetosphere, Solar Science, Heliosphere, Spa...",2026-04-29 11:58:54,C:\Users\shoffma5\Box\HESTO\HTIDeS\24-HTIDS\24...,Yes
3,C:\Users\shoffma5\Box\HESTO\HTIDeS\24-HTIDS\24...,24-HTIDS24-0025 (80NSSC25K7661),2026-04-26,2024,Gregory P. Miller,"Southwest Research Institute, San Antonio, TX","Magnetosphere, ITM",2026-04-26 16:14:23,C:\Users\shoffma5\Box\HESTO\HTIDeS\24-HTIDS\24...,Yes
4,C:\Users\shoffma5\Box\HESTO\HTIDeS\24-HTIDS\24...,24-HTIDS24-0036,2026-04-04,2024,Maria Usanova,University of Colorado Boulder,Magnetosphere,2026-04-24 16:39:00,C:\Users\shoffma5\Box\HESTO\HTIDeS\24-HTIDS\24...,Yes
5,C:\Users\shoffma5\Box\HESTO\HTIDeS\24-HTIDS\24...,24-HTIDS24-0039,2026-05-15,2024,Dhirendra Kataria,"Southwest Research Institute, San Antonio",Magnetosphere,2026-06-09 15:58:16,C:\Users\shoffma5\Box\HESTO\HTIDeS\24-HTIDS\24...,Yes
6,C:\Users\shoffma5\Box\HESTO\HTIDeS\23-HTIDS\23...,23-HTIDS23-0001,2026-05-05,2023,Mark Moldwin,University of Michigan,"Magnetosphere, ITM, Space Weather",2026-05-08 08:59:06,C:\Users\shoffma5\Box\HESTO\HTIDeS\23-HTIDS\23...,Yes
7,C:\Users\shoffma5\Box\HESTO\HTIDeS\23-HTIDS\23...,23-HTIDS23-0022,2026-04-15,2023,Ed Thiemann,"University of Colorado, LASP",ITM,2026-04-23 11:13:11,C:\Users\shoffma5\Box\HESTO\HTIDeS\23-HTIDS\23...,Yes
8,C:\Users\shoffma5\Box\HESTO\HTIDeS\23-HTIDS\23...,23-HTIDS23-0016,2026-04-27,2023,Juliana Vievering,Johns Hopkins Applied Physics Laboratory,Solar Science,2026-04-26 12:19:52,C:\Users\shoffma5\Box\HESTO\HTIDeS\23-HTIDS\23...,Yes
9,C:\Users\shoffma5\Box\HESTO\HTIDeS\23-HTIDS\23...,"23-HTIDS23-0011, 24-PIMOVE2-0048",2026-04-30,2023,Jongsoo Yoo,Princeton University/Princeton Plasma Physics ...,Magnetosphere/Heliosphere/Solar Science,2026-04-23 15:01:00,C:\Users\shoffma5\Box\HESTO\HTIDeS\23-HTIDS\23...,Yes
10,C:\Users\shoffma5\Box\HESTO\HTIDeS\23-HTIDS\23...,23-HTIDS23-0004,2026-05-13,2023,Jerry Goldstein,Southwest Research Institute (SwRI),Ionosphere-Thermosphere-Mesosphere (ITM),2026-04-26 15:05:51,C:\Users\shoffma5\Box\HESTO\HTIDeS\23-HTIDS\23...,Yes
11,C:\Users\shoffma5\Box\HESTO\HTIDeS\22-HTIDS\22...,22-HTIDS22-0008,2026-04-26,2022,Konstantinos Kalogerakis,SRI International,Ionosphere Thermosphere Mesosphere (ITM),2026-04-26 20:35:28,C:\Users\shoffma5\Box\HESTO\HTIDeS\22-HTIDS\22...,Yes
12,C:\Users\shoffma5\Box\HESTO\HTIDeS\22-HTIDS\22...,22-HTIDS22-0023,2026-04-15,2022,Justin H. Lee,The Aerospace Corporation,"Magnetosphere, Heliosphere, Space Weather",2026-05-26 13:22:32,C:\Users\shoffma5\Box\HESTO\HTIDeS\22-HTIDS\22...,Yes
13,C:\Users\shoffma5\Box\HESTO\HTIDeS\22-HTIDS\22...,22-HTIDS22-0020,2026-04-26,2022,John McVey,The Aerospace Corporation,System Inter-Disciplinary,2026-04-27 23:07:56,C:\Users\shoffma5\Box\HESTO\HTIDeS\22-HTIDS\22...,Yes
14,C:\Users\shoffma5\Box\HESTO\HTIDeS\22-HTIDS\22...,22-HTIDS22-0007,2026-05-04,2022,Majd Mayyasi,Boston University,"Heliosphere and Interdisciplinary (Helio, Eart...",2026-05-04 09:30:06,C:\Users\shoffma5\Box\HESTO\HTIDeS\22-HTIDS\22...,Yes
15,C:\Users\shoffma5\Box\HESTO\HTIDeS\22-HTIDS\22...,22-HTIDS22-0014,2026-04-15,2022,David Malaspina,"University of Colorado, Boulder","Magnetosphere, ITM, Space Weather",2026-04-20 22:00:13,C:\Users\shoffma5\Box\HESTO\HTIDeS\22-HTIDS\22...,Yes
16,C:\Users\shoffma5\Box\HESTO\HTIDeS\22-HTIDS\22...,22-HTIDS22-0004,2026-04-27,2022,Jeff Newmark,NASA GSFC,"Solar Science, Solar Atmosphere – Corona,\nSpa...",2026-04-22 09:58:11,C:\Users\shoffma5\Box\HESTO\HTIDeS\22-HTIDS\22...,Yes
17,C:\Users\shoffma5\Box\HESTO\HTIDeS\21-HTIDS\21...,21-HTIDS21-0004,2026-04-18,2021,Ethan Tsai,"University of California, Los Angeles",Heliosphere,2026-04-27 04:29:26,C:\Users\shoffma5\Box\HESTO\HTIDeS\21-HTIDS\21...,Yes
18,C:\Users\shoffma5\Box\HESTO\HTIDeS\21-HTIDS\21...,21-HTIDS21-0012,2026-05-01,2021,James Clemmons,University of New Hampshire,Ionosphere-Thermosphere-Mesosphere (ITM),2026-05-04 13:52:54,C:\Users\shoffma5\Box\HESTO\HTIDeS\21-HTIDS\21...,Yes
19,C:\Users\shoffma5\Box\HESTO\HTIDeS\20-HTIDS\20...,20-HTIDS20-0034,2026-04-26,2020,Hong Zhao,Auburn University,Magnetosphere,2026-04-26 09:46:23,C:\Users\shoffma5\Box\HESTO\HTIDeS\20-HTIDS\20...,Yes
20,C:\Users\shoffma5\Box\HESTO\HTIDeS\20-HTIDS\20...,20-HTIDS20-0010,2026-04-15,2020,John W. Bonnell,Space Sciences Laboratory\nUniversity of Calif...,"Magnetosphere, ITM, Heliosphere.",2026-05-04 18:51:59,C:\Users\shoffma5\Box\HESTO\HTIDeS\20-HTIDS\20...,Yes
21,C:\Users\shoffma5\Box\HESTO\HFOS\24-HFOS\24-HF...,24-HFOS24-0013,2026-04-29,2024,Greg Holsclaw,University of Colorado,Ionosphere-Thermosphere-Mesosphere (ITM),2026-04-29 18:57:30,C:\Users\shoffma5\Box\HESTO\HFOS\24-HFOS\24-HF...,Yes
22,C:\Users\shoffma5\Box\HESTO\HFOS\24-HFOS\24-HF...,24-HFOS24-0008,2026-04-24,2024,Dr. Christopher S. Moore,Harvard-Smithsonian Center for Astrophysics,Solar Science and Space Weather,2026-04-26 23:07:41,C:\Users\shoffma5\Box\HESTO\HFOS\24-HFOS\24-HF...,Yes
23,C:\Users\shoffma5\Box\HESTO\HFOS\23-HFOS\23-HF...,23-HFOS23-0003,2026-04-26,2023,Hong Zhao,Auburn University,Magnetosphere,2026-04-26 09:33:58,C:\Users\shoffma5\Box\HESTO\HFOS\23-HFOS\23-HF...,Yes

In [9]:
frames = []

def add_table(df, label):
    if df is not None:
        df = df.copy()
        df["table"] = label
        frames.append(df)

add_table(test_report.student_metrics_table, "student_metrics")
add_table(test_report.accomodation_table, "accomodation")
add_table(test_report.publication_table, "publications")
add_table(test_report.patents_table, "patents")
add_table(test_report.project_status, "project_status")

combined = pd.concat(frames, ignore_index=True)
combined

,Student Name (first last),Major,"Affiliation (School, University, etc.)","Level (High School, Undergrad, Grad, PhD)",table,category,sub_category,value,Type choose one of below,Title,Publication/Presentation Date,Publisher/Conference Name,URL,"Type (Issued, Filing)",Name,Patent or License Number,Date,"Resource Link (e.g., Google Patents Link)",prior,current
0,John Doe,Physics,University of Alabama,Undergrad,student_metrics,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,accomodation,payload size,length,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,accomodation,payload size,width,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,accomodation,payload size,height,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,accomodation,payload volume,,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,accomodation,power requirements,average,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,accomodation,power requirements,peak,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,accomodation,mass,,5.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,accomodation,pointing requirements,arcsecs,60.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,accomodation,pointing requirements,arcminutes,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,NaN,NaN,NaN,accomodation,data rate,average,15.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,NaN,NaN,NaN,accomodation,data rate,peak,100.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,NaN,NaN,NaN,NaN,accomodation,power interface port,,"db-9, 28 v, 1a",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,NaN,NaN,NaN,NaN,accomodation,communication interface protocol,,uart,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,NaN,NaN,NaN,NaN,accomodation,data communication port,,db-9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,NaN,NaN,NaN,NaN,accomodation,requires thermal isolation,,false,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,NaN,NaN,NaN,NaN,accomodation,special power considerations,,none,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,NaN,NaN,NaN,NaN,publications,NaN,NaN,NaN,Conference presentation (oral),Development of the Next-Generation Solar X-ray...,23-Jan-2026,IEEE NSS/MIC,https://ieeexplore.ieee.org/document/10657175,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,NaN,NaN,NaN,NaN,patents,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Issued,Art of transmitting electrical energy through ...,US787412A,1900-05-16,https://patents.google.com/patent/US787412A/,NaN,NaN
19,NaN,NaN,NaN,NaN,project_status,cost,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,y,y
20,NaN,NaN,NaN,NaN,project_status,schedule,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,g,g
21,NaN,NaN,NaN,NaN,project_status,technical,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,g,g
22,NaN,NaN,NaN,NaN,project_status,staffing,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,g,g
23,NaN,NaN,NaN,NaN,project_status,facilities,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,g,g
24,NaN,NaN,NaN,NaN,project_status,overall,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,y,y

In [10]:
files[files['year'] == 2024]

,file_path,project_id,report_date,year,principal_investigator,affiliation,research_regime,modified,folder,is_active
0,C:\Users\shoffma5\Box\HESTO\HTIDeS\24-HTIDS\24...,24-HTIDS24-0022,2026-05-11,2024,Lindsay Glesener,University of Minnesota,"Solar Science, Heliosphere, Space Weather",2026-06-10 10:51:52,C:\Users\shoffma5\Box\HESTO\HTIDeS\24-HTIDS\24...,Yes
1,C:\Users\shoffma5\Box\HESTO\HTIDeS\24-HTIDS\24...,24-HTIDS24-0005,2026-04-15,2024,Georgia de Nolfo,NASA Goddard Space Flight Center,"Solar Science, Heliosphere, Space Weather",2026-04-26 13:47:32,C:\Users\shoffma5\Box\HESTO\HTIDeS\24-HTIDS\24...,Yes
2,C:\Users\shoffma5\Box\HESTO\HTIDeS\24-HTIDS\24...,24-HTIDS24-0006,2026-04-30,2024,Shawn Liang,Johns Hopkins University Applied Physics Labor...,"Magnetosphere, Solar Science, Heliosphere, Spa...",2026-04-29 11:58:54,C:\Users\shoffma5\Box\HESTO\HTIDeS\24-HTIDS\24...,Yes
3,C:\Users\shoffma5\Box\HESTO\HTIDeS\24-HTIDS\24...,24-HTIDS24-0025 (80NSSC25K7661),2026-04-26,2024,Gregory P. Miller,"Southwest Research Institute, San Antonio, TX","Magnetosphere, ITM",2026-04-26 16:14:23,C:\Users\shoffma5\Box\HESTO\HTIDeS\24-HTIDS\24...,Yes
4,C:\Users\shoffma5\Box\HESTO\HTIDeS\24-HTIDS\24...,24-HTIDS24-0036,2026-04-04,2024,Maria Usanova,University of Colorado Boulder,Magnetosphere,2026-04-24 16:39:00,C:\Users\shoffma5\Box\HESTO\HTIDeS\24-HTIDS\24...,Yes
5,C:\Users\shoffma5\Box\HESTO\HTIDeS\24-HTIDS\24...,24-HTIDS24-0039,2026-05-15,2024,Dhirendra Kataria,"Southwest Research Institute, San Antonio",Magnetosphere,2026-06-09 15:58:16,C:\Users\shoffma5\Box\HESTO\HTIDeS\24-HTIDS\24...,Yes
21,C:\Users\shoffma5\Box\HESTO\HFOS\24-HFOS\24-HF...,24-HFOS24-0013,2026-04-29,2024,Greg Holsclaw,University of Colorado,Ionosphere-Thermosphere-Mesosphere (ITM),2026-04-29 18:57:30,C:\Users\shoffma5\Box\HESTO\HFOS\24-HFOS\24-HF...,Yes
22,C:\Users\shoffma5\Box\HESTO\HFOS\24-HFOS\24-HF...,24-HFOS24-0008,2026-04-24,2024,Dr. Christopher S. Moore,Harvard-Smithsonian Center for Astrophysics,Solar Science and Space Weather,2026-04-26 23:07:41,C:\Users\shoffma5\Box\HESTO\HFOS\24-HFOS\24-HF...,Yes

In [11]:
test_file = files[files['year'] == 2024].iloc[0]['file_path']

In [12]:
this_report = Report(test_file)

HESTO-202605_TriannualReport_23-HTIDS24-0022_PI-Glesener-rev4.pptx: unrecognised publication type 'Peer-reviewed journal'. Expected one of: ['Peer-reviewed publication', 'Non-Peer-reviewed publication', 'Conference presentation (oral)', 'Conference presentation (poster)', 'Web article']
HESTO-202605_TriannualReport_23-HTIDS24-0022_PI-Glesener-rev4.pptx: unrecognised publication type 'Non-peer-reviewed journal'. Expected one of: ['Peer-reviewed publication', 'Non-Peer-reviewed publication', 'Conference presentation (oral)', 'Conference presentation (poster)', 'Web article']

In [13]:
this_report

Report HESTO-202605_TriannualReport_23-HTIDS24-0022_PI-Glesener-rev4.pptx (35 slides)
Project ID: 24-HTIDS24-0022, PI: Lindsay Glesener

Accommodation:
Category                          Sub-category  Value
--------------------------------  ----------  -------------------------------
payload size                      length      10.0
                                  width       10.0
                                  height      20.0
payload volume                                2u
power requirements                            approx. 10 w average
mass                                          tbd
pointing requirements             arcsecs     ~1 deg abs. knowledge
                                  arcminutes  sun-pointed.
data rate                                     peak 128 mbps
power interface port                          d-sub 9-pin connector (tbr).
communication interface protocol              uart (rs-422) or ethernet, tbd.
data communication port                       db-9 (tbr).
requires thermal isolation                    false
special power considerations                  tbd

Publications:
        Type choose one of below Title Publication/Presentation Date Publisher/Conference Name URL
           Peer-reviewed journal
       Non-peer-reviewed journal
  Conference presentation (oral)
Conference presentation (poster)
                     Web article

In [14]:
this_report.accomodation_table

,category,sub_category,value
0,payload size,length,10.0
1,payload size,width,10.0
2,payload size,height,20.0
3,payload volume,,2u
4,power requirements,,approx. 10 w average
5,mass,,tbd
6,pointing requirements,arcsecs,~1 deg abs. knowledge
7,pointing requirements,arcminutes,sun-pointed.
8,data rate,,peak 128 mbps
9,power interface port,,d-sub 9-pin connector (tbr).
10,communication interface protocol,,"uart (rs-422) or ethernet, tbd."
11,data communication port,,db-9 (tbr).
12,requires thermal isolation,,false
13,special power considerations,,tbd

In [15]:
this_report.publication_table

,Type choose one of below,Title,Publication/Presentation Date,Publisher/Conference Name,URL
0,Peer-reviewed journal,,,,
1,Non-peer-reviewed journal,,,,
2,Conference presentation (oral),,,,
3,Conference presentation (poster),,,,
4,Web article,,,,

In [16]:
this_report.project_status

In [17]:
this_report.patents_table

In [18]:
test_file = files[files['year'] == 2024].iloc[1]['file_path']
test_file

WindowsPath('C:/Users/shoffma5/Box/HESTO/HTIDeS/24-HTIDS/24-HTIDS24-0005 Georgia de Nolfo/Reports/HESTO/HESTO-202605_Report_Proposal0005_deNolfo_v1.pptx')

In [19]:
this_report = Report(test_file)

HESTO-202605_Report_Proposal0005_deNolfo_v1.pptx: unrecognised publication type 'Poster presentation'. Expected one of: ['Peer-reviewed publication', 'Non-Peer-reviewed publication', 'Conference presentation (oral)', 'Conference presentation (poster)', 'Web article']
HESTO-202605_Report_Proposal0005_deNolfo_v1.pptx: unrecognised publication type 'Presentation/Session'. Expected one of: ['Peer-reviewed publication', 'Non-Peer-reviewed publication', 'Conference presentation (oral)', 'Conference presentation (poster)', 'Web article']
HESTO-202605_Report_Proposal0005_deNolfo_v1.pptx: unrecognised publication type 'Presentation'. Expected one of: ['Peer-reviewed publication', 'Non-Peer-reviewed publication', 'Conference presentation (oral)', 'Conference presentation (poster)', 'Web article']
HESTO-202605_Report_Proposal0005_deNolfo_v1.pptx: unrecognised publication type 'Presentation'. Expected one of: ['Peer-reviewed publication', 'Non-Peer-reviewed publication', 'Conference presentation (oral)', 'Conference presentation (poster)', 'Web article']
HESTO-202605_Report_Proposal0005_deNolfo_v1.pptx: unrecognised publication type 'Presentation'. Expected one of: ['Peer-reviewed publication', 'Non-Peer-reviewed publication', 'Conference presentation (oral)', 'Conference presentation (poster)', 'Web article']
HESTO-202605_Report_Proposal0005_deNolfo_v1.pptx: unrecognised publication type 'Presentation'. Expected one of: ['Peer-reviewed publication', 'Non-Peer-reviewed publication', 'Conference presentation (oral)', 'Conference presentation (poster)', 'Web article']
HESTO-202605_Report_Proposal0005_deNolfo_v1.pptx: unrecognised publication type 'Presentation'. Expected one of: ['Peer-reviewed publication', 'Non-Peer-reviewed publication', 'Conference presentation (oral)', 'Conference presentation (poster)', 'Web article']
HESTO-202605_Report_Proposal0005_deNolfo_v1.pptx: unrecognised publication type 'Presentation'. Expected one of: ['Peer-reviewed publication', 'Non-Peer-reviewed publication', 'Conference presentation (oral)', 'Conference presentation (poster)', 'Web article']
HESTO-202605_Report_Proposal0005_deNolfo_v1.pptx: unrecognised publication type 'Peer-reviewed Publication'. Expected one of: ['Peer-reviewed publication', 'Non-Peer-reviewed publication', 'Conference presentation (oral)', 'Conference presentation (poster)', 'Web article']
HESTO-202605_Report_Proposal0005_deNolfo_v1.pptx: unrecognised publication type 'Presentation'. Expected one of: ['Peer-reviewed publication', 'Non-Peer-reviewed publication', 'Conference presentation (oral)', 'Conference presentation (poster)', 'Web article']
HESTO-202605_Report_Proposal0005_deNolfo_v1.pptx: unrecognised publication type 'Presentation'. Expected one of: ['Peer-reviewed publication', 'Non-Peer-reviewed publication', 'Conference presentation (oral)', 'Conference presentation (poster)', 'Web article']
HESTO-202605_Report_Proposal0005_deNolfo_v1.pptx: unrecognised publication type 'PhD Dissertation'. Expected one of: ['Peer-reviewed publication', 'Non-Peer-reviewed publication', 'Conference presentation (oral)', 'Conference presentation (poster)', 'Web article']
HESTO-202605_Report_Proposal0005_deNolfo_v1.pptx: unrecognised publication type 'PhD Dissertation'. Expected one of: ['Peer-reviewed publication', 'Non-Peer-reviewed publication', 'Conference presentation (oral)', 'Conference presentation (poster)', 'Web article']
HESTO-202605_Report_Proposal0005_deNolfo_v1.pptx: unrecognised publication type 'Presentation'. Expected one of: ['Peer-reviewed publication', 'Non-Peer-reviewed publication', 'Conference presentation (oral)', 'Conference presentation (poster)', 'Web article']
HESTO-202605_Report_Proposal0005_deNolfo_v1.pptx: unrecognised publication type 'Presentation'. Expected one of: ['Peer-reviewed publication', 'Non-Peer-reviewed publication', 'Conference presentation (oral)', 'Conference presentation (poster)', 'Web article']

In [20]:
this_report.accomodation_table

                            category sub_category           value
0                       payload size       length            10.0
1                       payload size        width            10.0
2                       payload size       height            10.0
3                     payload volume                          1.0
4                 power requirements      average             5.0
5                 power requirements         peak            10.0
6                               mass                          5.4
7              pointing requirements      arcsecs            60.0
8              pointing requirements   arcminutes             1.0
9                          data rate      average            15.0
10                         data rate         peak           100.0
11              power interface port               db-9, 28 v, 1a
12  communication interface protocol                         uart
13           data communication port                         db-9
14        requires thermal isolation                        false
15      special power considerations                         none

In [21]:
this_report.summary

{'date': 'April 2026',
 'proposal title': 'Solar Neutron Tracking (SONTRAC) instrument',
 'technology name (acronym)': 'SONTRAC',
 'principal investigator': 'Georgia de Nolfo',
 'pi email': 'Georgia.a.denolfo@nasa.gov',
 'affiliation': 'NASA Goddard Space Flight Center',
 'proposal id': '24-HTIDS24-0005',
 'research regime': 'Solar Science, Heliosphere, Space Weather',
 'hesto taxonomy': 'TX08.3.1 Field and Particle Detectors; 3.4 & 3.6',
 'instrument type(s)': 'Neutron imaging spectrometer',
 'technology keyword': 'spectrometer',
 'project summary (two to three sentences)': 'The goal of the SOlar Neutron TRACking (SONTRAC) three-year program is to advance the current instrument development to provide a fully-integrated prototype that demonstrates suitability for SmallSAT opportunities.\xa0 SONTRAC addresses the following science questions: 1) do solar flares typically exhibit prolonged acceleration, 2) are the impulsive and extended phases of flares related, and 3) what is the maximum particle energy for a given flare and how do long duration γ-ray flares evolve?',
 'techport url': 'https://ntrs.nasa.gov/citations/20190034092'}