# Hesto Notebook (uv environment)
This notebook is configured to use the workspace Python environment managed by uv (.venv).

In [1]:
import sys
import pandas as pd
from pathlib import Path

print(sys.executable)

c:\Users\shoffma5\Documents\GitHub_orig\hestodb\.venv\Scripts\python.exe

In [2]:
from hestodb.util import find_latest_report_pptx
from hestodb.report import Report
from hestodb import _test_report_pptx

print(_test_report_pptx)

c:\Users\shoffma5\Documents\GitHub_orig\hestodb\hestodb\data\test\HESTO-202612_Report_24-HTIDS24_Smith-rev3.pptx

Checking the test file

In [3]:
test_report = Report(_test_report_pptx)
print(test_report)

Report HESTO-202612_Report_24-HTIDS24_Smith-rev3.pptx (33 slides)
Project ID: 24-HTIDS24-0009, PI: Jane Smith

Category    Prior    Current
----------  -------  -------
overall     Y        Y
cost        Y        Y
schedule    G        G
technical   G        G
staffing    G        G
facilities  G        G

Accommodation:
Category                          Sub-category  Value
--------------------------------  ----------  --------------
payload size                      length      10.0
                                  width       10.0
                                  height      10.0
payload volume                                1.0
power requirements                average     5.0
                                  peak        10.0
mass                                          5.4
pointing requirements             arcsecs     60.0
                                  arcminutes  1.0
data rate                         average     15.0
                                  peak        100.0
power interface port                          db-9, 28 v, 1a
communication interface protocol              uart
data communication port                       db-9
requires thermal isolation                    false
special power considerations                  none

Publications:
      Type choose one of below                                                   Title Publication/Presentation Date Publisher/Conference Name                                           URL
Conference presentation (oral) Development of the Next-Generation Solar X-ray detector                   23-Jan-2026              IEEE NSS/MIC https://ieeexplore.ieee.org/document/10657175

In [4]:
test_report.accomodation_table

                            category sub_category           value
0                       payload size       length            10.0
1                       payload size        width            10.0
2                       payload size       height            10.0
3                     payload volume                          1.0
4                 power requirements      average             5.0
5                 power requirements         peak            10.0
6                               mass                          5.4
7              pointing requirements      arcsecs            60.0
8              pointing requirements   arcminutes             1.0
9                          data rate      average            15.0
10                         data rate         peak           100.0
11              power interface port               db-9, 28 v, 1a
12  communication interface protocol                         uart
13           data communication port                         db-9
14        requires thermal isolation                        false
15      special power considerations                         none

In [5]:
test_report.publication_table

,Type choose one of below,Title,Publication/Presentation Date,Publisher/Conference Name,URL
0,Conference presentation (oral),Development of the Next-Generation Solar X-ray...,23-Jan-2026,IEEE NSS/MIC,https://ieeexplore.ieee.org/document/10657175

In [6]:
test_report.patents_table

,"Type (Issued, Filing)",Name,Patent or License Number,Date,"Resource Link (e.g., Google Patents Link)"
0,Issued,Art of transmitting electrical energy through ...,US787412A,1900-05-16,https://patents.google.com/patent/US787412A/

In [7]:
test_report.student_metrics_table

,Student Name (first last),Major,"Affiliation (School, University, etc.)","Level (High School, Undergrad, Grad, PhD)"
0,John Doe,Physics,University of Alabama,Undergrad

In [8]:
files = [
    find_latest_report_pptx(Path("C:\\Users\\shoffma5\\Box\\HESTO\\HTIDeS")),
    find_latest_report_pptx(Path("C:\\Users\\shoffma5\\Box\\HESTO\\HFOS")),
    find_latest_report_pptx(Path("C:\\Users\\shoffma5\\Box\\HESTO\\Special Projects")),
]
files = pd.concat(files, ignore_index=True).reset_index()
reports = [Report(p) for p in files["file_path"]]
print(f"Found {len(reports)} report files:")
files.to_csv("report_files.csv", index=False)
files

HESTO-202607_TriannualReport_19-HTIDS19-0027_Yee - NEW TEMPLATE.pptx: 'research regime' has no recognised value (got 'Ionosphere-Thermosphere-Mesosphere'). Expected one or more of: ['magnetosphere', 'itm', 'solar science', 'space weather', 'heliosphere']
HESTO-202607_TriannualReport_19-HTIDS19-0027_Yee - NEW TEMPLATE.pptx: status category 'overall' has invalid current value ''. Expected one of: ['g', 'y', 'r', 'green', 'yellow', 'red']
HESTO-202607_TriannualReport_19-HTIDS19-0027_Yee - NEW TEMPLATE.pptx: status category 'cost' has invalid current value ''. Expected one of: ['g', 'y', 'r', 'green', 'yellow', 'red']
HESTO-202607_TriannualReport_19-HTIDS19-0027_Yee - NEW TEMPLATE.pptx: status category 'schedule' has invalid current value ''. Expected one of: ['g', 'y', 'r', 'green', 'yellow', 'red']
HESTO-202607_TriannualReport_19-HTIDS19-0027_Yee - NEW TEMPLATE.pptx: status category 'technical' has invalid current value ''. Expected one of: ['g', 'y', 'r', 'green', 'yellow', 'red']
HESTO-202607_TriannualReport_19-HTIDS19-0027_Yee - NEW TEMPLATE.pptx: status category 'staffing' has invalid current value ''. Expected one of: ['g', 'y', 'r', 'green', 'yellow', 'red']
HESTO-202607_TriannualReport_19-HTIDS19-0027_Yee - NEW TEMPLATE.pptx: status category 'facilities' has invalid current value ''. Expected one of: ['g', 'y', 'r', 'green', 'yellow', 'red']
HESTO-202607_TriannualReport_19-HTIDS19-0027_Yee - NEW TEMPLATE.pptx: unrecognised publication type 'Conference presentation'. Expected one of: ['Peer-reviewed publication', 'Non-Peer-reviewed publication', 'Conference presentation (oral)', 'Conference presentation (poster)', 'Web article']
HESTO-202607_TriannualReport_19-HTIDS19-0027_Yee - NEW TEMPLATE.pptx: unrecognised publication type 'Conference'. Expected one of: ['Peer-reviewed publication', 'Non-Peer-reviewed publication', 'Conference presentation (oral)', 'Conference presentation (poster)', 'Web article']
HESTO-202607_TriannualReport_19-HTIDS19-0027_Yee - NEW TEMPLATE.pptx: unrecognised publication type 'Conference'. Expected one of: ['Peer-reviewed publication', 'Non-Peer-reviewed publication', 'Conference presentation (oral)', 'Conference presentation (poster)', 'Web article']
HESTO-202607_TriannualReport_19-HTIDS19-0027_Yee - NEW TEMPLATE.pptx: unrecognised publication type 'Peer reviewed IEEE publication'. Expected one of: ['Peer-reviewed publication', 'Non-Peer-reviewed publication', 'Conference presentation (oral)', 'Conference presentation (poster)', 'Web article']
HESTO-202607_TriannualReport_19-HTIDS19-0027_Yee - NEW TEMPLATE.pptx: unrecognised publication type 'Peer reviewed IEEE publication'. Expected one of: ['Peer-reviewed publication', 'Non-Peer-reviewed publication', 'Conference presentation (oral)', 'Conference presentation (poster)', 'Web article']
HESTO-202607_TriannualReport_19-HTIDS19-0027_Yee - NEW TEMPLATE.pptx: unrecognised publication type 'Conference'. Expected one of: ['Peer-reviewed publication', 'Non-Peer-reviewed publication', 'Conference presentation (oral)', 'Conference presentation (poster)', 'Web article']
HESTO-202607_TriannualReport_19-HTIDS19-0027_Yee - NEW TEMPLATE.pptx: unrecognised publication type 'HELIOTECH'. Expected one of: ['Peer-reviewed publication', 'Non-Peer-reviewed publication', 'Conference presentation (oral)', 'Conference presentation (poster)', 'Web article']
HESTO-202607_TriannualReport_19-HTIDS19-0027_Yee - NEW TEMPLATE.pptx: unrecognised publication type 'Peer reviewed IEEE journal publication'. Expected one of: ['Peer-reviewed publication', 'Non-Peer-reviewed publication', 'Conference presentation (oral)', 'Conference presentation (poster)', 'Web article']
HESTO-202607_TriannualReport_19-HTIDS19-0027_Yee - NEW TEMPLATE.pptx: unrecognised publication type 'Conference presentation'. Expected one of: ['Peer-reviewed publication', 'Non-Peer-reviewed publication', 'Conference presentation (oral)', 'Conference presentation (poster)', 'Web article']
HESTO-202607_TriannualReport_19-HTIDS19-0027_Yee - NEW TEMPLATE.pptx: unrecognised publication type 'Conference presentation'. Expected one of: ['Peer-reviewed publication', 'Non-Peer-reviewed publication', 'Conference presentation (oral)', 'Conference presentation (poster)', 'Web article']
HESTO-202607_TriannualReport_19-HTIDS19-0027_Yee - NEW TEMPLATE.pptx: unrecognised publication type 'Seminar'. Expected one of: ['Peer-reviewed publication', 'Non-Peer-reviewed publication', 'Conference presentation (oral)', 'Conference presentation (poster)', 'Web article']
HESTO-202601_TriannualReport_20-HTIDS20-0004_Sewell.pptx: unrecognised publication type 'Design Review'. Expected one of: ['Peer-reviewed publication', 'Non-Peer-reviewed publication', 'Conference presentation (oral)', 'Conference presentation (poster)', 'Web article']
HESTO-202601_TriannualReport_20-HTIDS20-0004_Sewell.pptx: unrecognised publication type 'Poster Presentation'. Expected one of: ['Peer-reviewed publication', 'Non-Peer-reviewed publication', 'Conference presentation (oral)', 'Conference presentation (poster)', 'Web article']
HESTO-202601_TriannualReport_20-HTIDS20-0004_Sewell.pptx: unrecognised publication type 'Design Review'. Expected one of: ['Peer-reviewed publication', 'Non-Peer-reviewed publication', 'Conference presentation (oral)', 'Conference presentation (poster)', 'Web article']
HESTO-202601_TriannualReport_20-HTIDS20-0004_Sewell.pptx: unrecognised publication type 'Oral Presentation'. Expected one of: ['Peer-reviewed publication', 'Non-Peer-reviewed publication', 'Conference presentation (oral)', 'Conference presentation (poster)', 'Web article']
HESTO-202601_TriannualReport_20-HTIDS20-00009_Cohen_v1.pptx: unrecognised publication type 'Poster'. Expected one of: ['Peer-reviewed publication', 'Non-Peer-reviewed publication', 'Conference presentation (oral)', 'Conference presentation (poster)', 'Web article']
HESTO-202601_TriannualReport_20-HTIDS20-00009_Cohen_v1.pptx: unrecognised publication type 'Talk'. Expected one of: ['Peer-reviewed publication', 'Non-Peer-reviewed publication', 'Conference presentation (oral)', 'Conference presentation (poster)', 'Web article']
HESTO-202601_TriannualReport_20-HTIDS20-00009_Cohen_v2.pptx: unrecognised publication type 'Poster'. Expected one of: ['Peer-reviewed publication', 'Non-Peer-reviewed publication', 'Conference presentation (oral)', 'Conference presentation (poster)', 'Web article']
HESTO-202601_TriannualReport_20-HTIDS20-00009_Cohen_v2.pptx: unrecognised publication type 'Talk'. Expected one of: ['Peer-reviewed publication', 'Non-Peer-reviewed publication', 'Conference presentation (oral)', 'Conference presentation (poster)', 'Web article']
HESTO-202605_TriannualReport_20-HTIDS20-00009_Cohen_v1.pptx: unrecognised publication type 'Poster'. Expected one of: ['Peer-reviewed publication', 'Non-Peer-reviewed publication', 'Conference presentation (oral)', 'Conference presentation (poster)', 'Web article']
HESTO-202605_TriannualReport_20-HTIDS20-00009_Cohen_v1.pptx: unrecognised publication type 'Talk'. Expected one of: ['Peer-reviewed publication', 'Non-Peer-reviewed publication', 'Conference presentation (oral)', 'Conference presentation (poster)', 'Web article']
HESTO-202607_TriannualReport_20-HTIDS20-00009_Cohen_v1 - NEW TEMPLATE.pptx: 'research regime' has no recognised value (got 'Interdisciplinary'). Expected one or more of: ['magnetosphere', 'itm', 'solar science', 'space weather', 'heliosphere']
HESTO-202601_TriannualReport_20-HTIDS20-0010_BONNELL-20260219-rev2.pptx: unrecognised publication type 'Oral'. Expected one of: ['Peer-reviewed publication', 'Non-Peer-reviewed publication', 'Conference presentation (oral)', 'Conference presentation (poster)', 'Web article']
HESTO-202601_TriannualReport_20-HTIDS20-0010_BONNELL-20260219-rev2.pptx: unrecognised publication type 'Oral'. Expected one of: ['Peer-reviewed publication', 'Non-Peer-reviewed publication', 'Conference presentation (oral)', 'Conference presentation (poster)', 'Web article']
HESTO-202601_TriannualReport_20-HTIDS20-0010_BONNELL-20260219-rev2.pptx: unrecognised publication type 'Oral/Poster'. Expected one of: ['Peer-reviewed publication', 'Non-Peer-reviewed publication', 'Conference presentation (oral)', 'Conference presentation (poster)', 'Web article']
HESTO-202601_TriannualReport_20-HTIDS20-0010_BONNELL-20260219-rev2.pptx: unrecognised publication type 'Oral'. Expected one of: ['Peer-reviewed publication', 'Non-Peer-reviewed publication', 'Conference presentation (oral)', 'Conference presentation (poster)', 'Web article']
HESTO-202601_TriannualReport_20-HTIDS20-0010_BONNELL-20260219-rev2.pptx: unrecognised publication type 'Oral'. Expected one of: ['Peer-reviewed publication', 'Non-Peer-reviewed publication', 'Conference presentation (oral)', 'Conference presentation (poster)', 'Web article']
HESTO-202601_TriannualReport_20-HTIDS20-0010_BONNELL-20260219-rev2.pptx: unrecognised publication type 'Oral'. Expected one of: ['Peer-reviewed publication', 'Non-Peer-reviewed publication', 'Conference presentation (oral)', 'Conference presentation (poster)', 'Web article']
HESTO-202601_TriannualReport_20-HTIDS20-0010_BONNELL-20260219-rev2.pptx: unrecognised publication type 'Oral'. Expected one of: ['Peer-reviewed publication', 'Non-Peer-reviewed publication', 'Conference presentation (oral)', 'Conference presentation (poster)', 'Web article']
HESTO-202601_TriannualReport_20-HTIDS20-0010_BONNELL-20260219-rev2.pptx: unrecognised publication type 'Oral'. Expected one of: ['Peer-reviewed publication', 'Non-Peer-reviewed publication', 'Conference presentation (oral)', 'Conference presentation (poster)', 'Web article']
HESTO-202601_TriannualReport_20-HTIDS20-0010_BONNELL-20260219-rev2.pptx: unrecognised publication type 'Oral'. Expected one of: ['Peer-reviewed publication', 'Non-Peer-reviewed publication', 'Conference presentation (oral)', 'Conference presentation (poster)', 'Web article']
HESTO-202601_TriannualReport_20-HTIDS20-0010_BONNELL-20260219-rev2.pptx: unrecognised publication type 'Poster'. Expected one of: ['Peer-reviewed publication', 'Non-Peer-reviewed publication', 'Conference presentation (oral)', 'Conference presentation (poster)', 'Web article']
HESTO-202601_TriannualReport_20-HTIDS20-0010_BONNELL-20260219-rev2.pptx: unrecognised publication type 'Oral'. Expected one of: ['Peer-reviewed publication', 'Non-Peer-reviewed publication', 'Conference presentation (oral)', 'Conference presentation (poster)', 'Web article']
HESTO-202604_TriannualReport_20-HTIDS20-0010_BONNELL-rev3.pptx: unrecognised publication type 'Peer-reviewed journal'. Expected one of: ['Peer-reviewed publication', 'Non-Peer-reviewed publication', 'Conference presentation (oral)', 'Conference presentation (poster)', 'Web article']
HESTO-202604_TriannualReport_20-HTIDS20-0010_BONNELL-rev3.pptx: unrecognised publication type 'Non-peer-reviewed journal'. Expected one of: ['Peer-reviewed publication', 'Non-Peer-reviewed publication', 'Conference presentation (oral)', 'Conference presentation (poster)', 'Web article']
HESTO-202607_TriannualReport_20-HTIDS20-0027_Fish - NEW TEMPLATE.pptx: 'research regime' has no recognised value (got 'Instrument Development'). Expected one or more of: ['magnetosphere', 'itm', 'solar science', 'space weather', 'heliosphere']
HESTO-202607_TriannualReport_20-HTIDS20-0027_Fish - NEW TEMPLATE.pptx: status category 'cost' has invalid current value ''. Expected one of: ['g', 'y', 'r', 'green', 'yellow', 'red']
HESTO-202607_TriannualReport_20-HTIDS20-0027_Fish - NEW TEMPLATE.pptx: status category 'schedule' has invalid current value ''. Expected one of: ['g', 'y', 'r', 'green', 'yellow', 'red']
HESTO-202607_TriannualReport_20-HTIDS20-0027_Fish - NEW TEMPLATE.pptx: status category 'technical' has invalid current value ''. Expected one of: ['g', 'y', 'r', 'green', 'yellow', 'red']
HESTO-202607_TriannualReport_20-HTIDS20-0027_Fish - NEW TEMPLATE.pptx: status category 'staffing' has invalid current value ''. Expected one of: ['g', 'y', 'r', 'green', 'yellow', 'red']
HESTO-202607_TriannualReport_20-HTIDS20-0027_Fish - NEW TEMPLATE.pptx: status category 'facilities' has invalid current value ''. Expected one of: ['g', 'y', 'r', 'green', 'yellow', 'red']
HESTO-202607_TriannualReport_20-HTIDS20-0027_Fish - NEW TEMPLATE.pptx: status category 'overall' has invalid current value ''. Expected one of: ['g', 'y', 'r', 'green', 'yellow', 'red']
HESTO-202607_TriannualReport_0028_Hosseini - NEW TEMPLATE.pptx: status category 'cost' has invalid current value ''. Expected one of: ['g', 'y', 'r', 'green', 'yellow', 'red']
HESTO-202607_TriannualReport_0028_Hosseini - NEW TEMPLATE.pptx: status category 'schedule' has invalid current value ''. Expected one of: ['g', 'y', 'r', 'green', 'yellow', 'red']
HESTO-202607_TriannualReport_0028_Hosseini - NEW TEMPLATE.pptx: status category 'technical' has invalid current value ''. Expected one of: ['g', 'y', 'r', 'green', 'yellow', 'red']
HESTO-202607_TriannualReport_0028_Hosseini - NEW TEMPLATE.pptx: status category 'staffing' has invalid current value ''. Expected one of: ['g', 'y', 'r', 'green', 'yellow', 'red']
HESTO-202607_TriannualReport_0028_Hosseini - NEW TEMPLATE.pptx: status category 'facilities' has invalid current value ''. Expected one of: ['g', 'y', 'r', 'green', 'yellow', 'red']
HESTO-202607_TriannualReport_0028_Hosseini - NEW TEMPLATE.pptx: status category 'overall' has invalid current value ''. Expected one of: ['g', 'y', 'r', 'green', 'yellow', 'red']
HESTO-202607_TriannualReport_0028_Hosseini - NEW TEMPLATE.pptx: unrecognised publication type 'Presentation'. Expected one of: ['Peer-reviewed publication', 'Non-Peer-reviewed publication', 'Conference presentation (oral)', 'Conference presentation (poster)', 'Web article']
HESTO-202607_TriannualReport_0028_Hosseini - NEW TEMPLATE.pptx: unrecognised publication type 'APL Report support'. Expected one of: ['Peer-reviewed publication', 'Non-Peer-reviewed publication', 'Conference presentation (oral)', 'Conference presentation (poster)', 'Web article']
HESTO-202607_TriannualReport_0028_Hosseini - NEW TEMPLATE.pptx: unrecognised publication type 'Presentation'. Expected one of: ['Peer-reviewed publication', 'Non-Peer-reviewed publication', 'Conference presentation (oral)', 'Conference presentation (poster)', 'Web article']
HESTO-202607_TriannualReport_0028_Hosseini - NEW TEMPLATE.pptx: unrecognised publication type 'Decadal Survey White paper'. Expected one of: ['Peer-reviewed publication', 'Non-Peer-reviewed publication', 'Conference presentation (oral)', 'Conference presentation (poster)', 'Web article']
HESTO-202607_TriannualReport_0028_Hosseini - NEW TEMPLATE.pptx: unrecognised publication type 'Conference Presentation / poster'. Expected one of: ['Peer-reviewed publication', 'Non-Peer-reviewed publication', 'Conference presentation (oral)', 'Conference presentation (poster)', 'Web article']
HESTO-202607_TriannualReport_0028_Hosseini - NEW TEMPLATE.pptx: unrecognised publication type 'Conference presentation / poster'. Expected one of: ['Peer-reviewed publication', 'Non-Peer-reviewed publication', 'Conference presentation (oral)', 'Conference presentation (poster)', 'Web article']
HESTO-202607_TriannualReport_0028_Hosseini - NEW TEMPLATE.pptx: unrecognised publication type 'Presentation'. Expected one of: ['Peer-reviewed publication', 'Non-Peer-reviewed publication', 'Conference presentation (oral)', 'Conference presentation (poster)', 'Web article']
HESTO-202607_TriannualReport_0028_Hosseini - NEW TEMPLATE.pptx: unrecognised publication type 'Journal paper'. Expected one of: ['Peer-reviewed publication', 'Non-Peer-reviewed publication', 'Conference presentation (oral)', 'Conference presentation (poster)', 'Web article']
HESTO-202602_TriannualReport_20-HTIDS20-0031_PIMouikis.pptx: unrecognised publication type 'Conference'. Expected one of: ['Peer-reviewed publication', 'Non-Peer-reviewed publication', 'Conference presentation (oral)', 'Conference presentation (poster)', 'Web article']
HESTO-202602_TriannualReport_20-HTIDS20-0031_PIMouikis.pptx: unrecognised publication type 'Conference'. Expected one of: ['Peer-reviewed publication', 'Non-Peer-reviewed publication', 'Conference presentation (oral)', 'Conference presentation (poster)', 'Web article']
HESTO-202602_TriannualReport_20-HTIDS20-0031_PIMouikis.pptx: unrecognised publication type 'Conference'. Expected one of: ['Peer-reviewed publication', 'Non-Peer-reviewed publication', 'Conference presentation (oral)', 'Conference presentation (poster)', 'Web article']
HESTO-202602_TriannualReport_20-HTIDS20-0031_PIMouikis.pptx: unrecognised publication type 'Conference'. Expected one of: ['Peer-reviewed publication', 'Non-Peer-reviewed publication', 'Conference presentation (oral)', 'Conference presentation (poster)', 'Web article']
HESTO-202602_TriannualReport_20-HTIDS20-0031_PIMouikis.pptx: unrecognised publication type 'Conference'. Expected one of: ['Peer-reviewed publication', 'Non-Peer-reviewed publication', 'Conference presentation (oral)', 'Conference presentation (poster)', 'Web article']
HESTO-202602_TriannualReport_20-HTIDS20-0031_PIMouikis.pptx: unrecognised publication type 'Publication'. Expected one of: ['Peer-reviewed publication', 'Non-Peer-reviewed publication', 'Conference presentation (oral)', 'Conference presentation (poster)', 'Web article']
HESTO-202602_TriannualReport_20-HTIDS20-0031_PIMouikis.pptx: unrecognised publication type 'Publication'. Expected one of: ['Peer-reviewed publication', 'Non-Peer-reviewed publication', 'Conference presentation (oral)', 'Conference presentation (poster)', 'Web article']
HESTO-202601_TriannualReport_20-HTIDS20-0034_Zhao.pptx: unrecognised publication type 'Presentation'. Expected one of: ['Peer-reviewed publication', 'Non-Peer-reviewed publication', 'Conference presentation (oral)', 'Conference presentation (poster)', 'Web article']
HESTO-202601_TriannualReport_20-HTIDS20-0034_Zhao.pptx: unrecognised publication type 'Presentation'. Expected one of: ['Peer-reviewed publication', 'Non-Peer-reviewed publication', 'Conference presentation (oral)', 'Conference presentation (poster)', 'Web article']
HESTO-202601_TriannualReport_20-HTIDS20-0034_Zhao.pptx: unrecognised publication type 'Presentation'. Expected one of: ['Peer-reviewed publication', 'Non-Peer-reviewed publication', 'Conference presentation (oral)', 'Conference presentation (poster)', 'Web article']
HESTO-202601_TriannualReport_20-HTIDS20-0034_Zhao.pptx: unrecognised publication type 'Presentation'. Expected one of: ['Peer-reviewed publication', 'Non-Peer-reviewed publication', 'Conference presentation (oral)', 'Conference presentation (poster)', 'Web article']
HESTO-202601_TriannualReport_20-HTIDS20-0034_Zhao.pptx: unrecognised publication type 'Presentation'. Expected one of: ['Peer-reviewed publication', 'Non-Peer-reviewed publication', 'Conference presentation (oral)', 'Conference presentation (poster)', 'Web article']
HESTO-202601_TriannualReport_20-HTIDS20-0034_Zhao.pptx: unrecognised publication type 'Presentation'. Expected one of: ['Peer-reviewed publication', 'Non-Peer-reviewed publication', 'Conference presentation (oral)', 'Conference presentation (poster)', 'Web article']
HESTO-202601_TriannualReport_20-HTIDS20-0034_Zhao.pptx: unrecognised publication type 'Presentation'. Expected one of: ['Peer-reviewed publication', 'Non-Peer-reviewed publication', 'Conference presentation (oral)', 'Conference presentation (poster)', 'Web article']
HESTO-202601_TriannualReport_20-HTIDS20-0034_Zhao.pptx: unrecognised publication type 'Publication'. Expected one of: ['Peer-reviewed publication', 'Non-Peer-reviewed publication', 'Conference presentation (oral)', 'Conference presentation (poster)', 'Web article']

Found 41 report files:

,index,file_path,project_id,report_date,year,principal_investigator,affiliation,research_regime,modified,folder,is_active
0,0,C:\Users\shoffma5\Box\HESTO\HTIDeS\24-HTIDS\24...,24-HTIDS24-0036,2026-04-04,2024,Maria Usanova,University of Colorado Boulder,Magnetosphere,2026-06-15 15:12:48,C:\Users\shoffma5\Box\HESTO\HTIDeS\24-HTIDS\24...,Yes
1,1,C:\Users\shoffma5\Box\HESTO\HTIDeS\24-HTIDS\24...,24-HTIDS24-0025 (80NSSC25K7661),2026-04-26,2024,Gregory P. Miller,"Southwest Research Institute, San Antonio, TX","Magnetosphere, ITM",2026-04-26 16:14:23,C:\Users\shoffma5\Box\HESTO\HTIDeS\24-HTIDS\24...,Yes
2,2,C:\Users\shoffma5\Box\HESTO\HTIDeS\24-HTIDS\24...,24-HTIDS24-0006,2026-04-30,2024,Shawn Liang,Johns Hopkins University Applied Physics Labor...,"Magnetosphere, Solar Science, Heliosphere, Spa...",2026-06-16 14:51:28,C:\Users\shoffma5\Box\HESTO\HTIDeS\24-HTIDS\24...,Yes
3,3,C:\Users\shoffma5\Box\HESTO\HTIDeS\24-HTIDS\24...,24-HTIDS24-0022,2026-05-11,2024,Lindsay Glesener,University of Minnesota,"Solar Science, Heliosphere, Space Weather",2026-06-10 10:51:52,C:\Users\shoffma5\Box\HESTO\HTIDeS\24-HTIDS\24...,Yes
4,4,C:\Users\shoffma5\Box\HESTO\HTIDeS\24-HTIDS\24...,24-HTIDS24-0039,2026-05-15,2024,Dhirendra Kataria,"Southwest Research Institute, San Antonio",Magnetosphere,2026-06-09 15:58:16,C:\Users\shoffma5\Box\HESTO\HTIDeS\24-HTIDS\24...,Yes
5,5,C:\Users\shoffma5\Box\HESTO\HTIDeS\24-HTIDS\24...,24-HTIDS24-0005,2026-05-15,2024,Georgia de Nolfo,NASA Goddard Space Flight Center,"Solar Science, Heliosphere, Space Weather",2026-04-26 13:47:32,C:\Users\shoffma5\Box\HESTO\HTIDeS\24-HTIDS\24...,Yes
6,6,C:\Users\shoffma5\Box\HESTO\HTIDeS\23-HTIDS\23...,23-HTIDS23-0016,2026-04-27,2023,Juliana Vievering,Johns Hopkins Applied Physics Laboratory,Solar Science,2026-04-26 12:19:52,C:\Users\shoffma5\Box\HESTO\HTIDeS\23-HTIDS\23...,Yes
7,7,C:\Users\shoffma5\Box\HESTO\HTIDeS\23-HTIDS\23...,23-HTIDS23-0001,2026-05-05,2023,Mark Moldwin,University of Michigan,"Magnetosphere, ITM, Space Weather",2026-06-16 15:18:11,C:\Users\shoffma5\Box\HESTO\HTIDeS\23-HTIDS\23...,Yes
8,8,C:\Users\shoffma5\Box\HESTO\HTIDeS\23-HTIDS\23...,23-HTIDS23-0004,2026-05-13,2023,Jerry Goldstein,Southwest Research Institute (SwRI),Ionosphere-Thermosphere-Mesosphere (ITM),2026-04-26 15:05:51,C:\Users\shoffma5\Box\HESTO\HTIDeS\23-HTIDS\23...,Yes
9,9,C:\Users\shoffma5\Box\HESTO\HTIDeS\23-HTIDS\23...,23-HTIDS23-0008,2026-07-15,2023,Amy Gall,Smithsonian Astrophysical Observatory (SAO),System Inter-Disciplinary,2026-06-16 16:13:40,C:\Users\shoffma5\Box\HESTO\HTIDeS\23-HTIDS\23...,Yes
10,10,C:\Users\shoffma5\Box\HESTO\HTIDeS\23-HTIDS\23...,"23-HTIDS23-0011, 24-PIMOVE2-0048",2026-07-15,2023,Jongsoo Yoo,Princeton University/Princeton Plasma Physics ...,Magnetosphere/Heliosphere/Solar Science,2026-06-17 09:00:25,C:\Users\shoffma5\Box\HESTO\HTIDeS\23-HTIDS\23...,Yes
11,11,C:\Users\shoffma5\Box\HESTO\HTIDeS\23-HTIDS\23...,23-HTIDS23-0017,2026-07-15,2023,Keiichi Ogasawara,Southwest Research Institute,System Inter-Disciplinary,2026-06-17 09:46:08,C:\Users\shoffma5\Box\HESTO\HTIDeS\23-HTIDS\23...,Yes
12,12,C:\Users\shoffma5\Box\HESTO\HTIDeS\23-HTIDS\23...,23-HTIDS23-0023,2026-07-15,2023,Aroh Barjatya,Embry-Riddle Aeronautical University,"Ionosphere-Thermosphere-Mesosphere, System Int...",2026-06-17 10:17:49,C:\Users\shoffma5\Box\HESTO\HTIDeS\23-HTIDS\23...,Yes
13,13,C:\Users\shoffma5\Box\HESTO\HTIDeS\23-HTIDS\23...,23-HTIDS23-0024,2026-07-15,2023,Carlos Maldonado,Los Alamos National Laboratory,System Inter-Disciplinary,2026-06-17 10:44:42,C:\Users\shoffma5\Box\HESTO\HTIDeS\23-HTIDS\23...,Yes
14,14,C:\Users\shoffma5\Box\HESTO\HTIDeS\23-HTIDS\23...,23-HTIDS23-0025,2026-07-15,2023,Joshua Eskin,BAE Systems SMS,Heliosphere,2026-06-17 10:58:01,C:\Users\shoffma5\Box\HESTO\HTIDeS\23-HTIDS\23...,Yes
15,15,C:\Users\shoffma5\Box\HESTO\HTIDeS\23-HTIDS\23...,23-HTIDS23-0012,2026-07-15,2023,Drew Turner,Johns Hopkins Applied Physics Laboratory,System Inter-Disciplinary,2026-06-17 09:12:51,C:\Users\shoffma5\Box\HESTO\HTIDeS\23-HTIDS\23...,Yes
16,16,C:\Users\shoffma5\Box\HESTO\HTIDeS\23-HTIDS\23...,23-HTIDS23-0022,2026-07-15,2023,Ed Thiemann,"University of Colorado, LASP",ITM,2026-06-17 09:58:47,C:\Users\shoffma5\Box\HESTO\HTIDeS\23-HTIDS\23...,Yes
17,17,C:\Users\shoffma5\Box\HESTO\HTIDeS\22-HTIDS\22...,22-HTIDS22-0013,2026-04-15,2022,Mihailo Martinovic,NaN,NaN,2026-04-25 20:14:14,C:\Users\shoffma5\Box\HESTO\HTIDeS\22-HTIDS\22...,Yes
18,18,C:\Users\shoffma5\Box\HESTO\HTIDeS\22-HTIDS\22...,22-HTIDS22-0020,2026-04-26,2022,John McVey,The Aerospace Corporation,System Inter-Disciplinary,2026-06-16 15:19:48,C:\Users\shoffma5\Box\HESTO\HTIDeS\22-HTIDS\22...,Yes
19,19,C:\Users\shoffma5\Box\HESTO\HTIDeS\22-HTIDS\22...,22-HTIDS22-0019,2026-07-27,2022,Feiyu Li,New Mexico Consortium,Heliosphere,2026-06-16 15:02:00,C:\Users\shoffma5\Box\HESTO\HTIDeS\22-HTIDS\22...,Yes
20,20,C:\Users\shoffma5\Box\HESTO\HTIDeS\22-HTIDS\22...,22-HTIDS22-0023,2026-07-15,2022,Justin H. Lee,The Aerospace Corporation,"Magnetosphere, Heliosphere, Space Weather",2026-06-16 16:00:28,C:\Users\shoffma5\Box\HESTO\HTIDeS\22-HTIDS\22...,Yes
21,21,C:\Users\shoffma5\Box\HESTO\HTIDeS\22-HTIDS\22...,22-HTIDS22-0006,2026-07-27,2022,Andrew Nicholas,Naval Research Laboratory,System Inter-Disciplinary,2026-06-16 14:41:15,C:\Users\shoffma5\Box\HESTO\HTIDeS\22-HTIDS\22...,Yes
22,22,C:\Users\shoffma5\Box\HESTO\HTIDeS\22-HTIDS\22...,22-HTIDS22-0014,2026-07-15,2022,David Malaspina,"University of Colorado, Boulder","Magnetosphere, ITM, Space Weather",2026-06-16 15:36:29,C:\Users\shoffma5\Box\HESTO\HTIDeS\22-HTIDS\22...,Yes
23,23,C:\Users\shoffma5\Box\HESTO\HTIDeS\22-HTIDS\22...,22-HTIDS22-0004,2026-07-15,2022,Jeff Newmark,NASA GSFC,"Solar Science, Solar Atmosphere – Corona, Spac...",2026-06-17 11:36:23,C:\Users\shoffma5\Box\HESTO\HTIDeS\22-HTIDS\22...,Yes
24,24,C:\Users\shoffma5\Box\HESTO\HTIDeS\22-HTIDS\22...,22-HTIDS22-0008,2026-07-15,2022,Konstantinos Kalogerakis,SRI International,Ionosphere Thermosphere Mesosphere (ITM),2026-06-17 11:59:22,C:\Users\shoffma5\Box\HESTO\HTIDeS\22-HTIDS\22...,Yes
25,25,C:\Users\shoffma5\Box\HESTO\HTIDeS\22-HTIDS\22...,22HTIDS-22-0018,2026-07-27,2022,Robert Clayton,Embry-Riddle Aeronautical University,ITM (Ionosphere-Thermosphere-Mesosphere),2026-06-16 15:50:03,C:\Users\shoffma5\Box\HESTO\HTIDeS\22-HTIDS\22...,Yes
26,26,C:\Users\shoffma5\Box\HESTO\HTIDeS\22-HTIDS\22...,22-HTIDS22-0007,2026-05-04,2022,Majd Mayyasi,Boston University,"Heliosphere and Interdisciplinary (Helio, Eart...",2026-05-04 09:30:06,C:\Users\shoffma5\Box\HESTO\HTIDeS\22-HTIDS\22...,Yes
27,27,C:\Users\shoffma5\Box\HESTO\HTIDeS\21-HTIDS\21...,21-HTIDS21-0012,2026-07-27,2021,James Clemmons,University of New Hampshire,Ionosphere-Thermosphere-Mesosphere (ITM),2026-06-16 14:07:38,C:\Users\shoffma5\Box\HESTO\HTIDeS\21-HTIDS\21...,Yes
28,28,C:\Users\shoffma5\Box\HESTO\HTIDeS\21-HTIDS\21...,XX-HTIDSXX-XXXX or XX-HFOSXX-XXXX,2026-07-15,2021,XXXX XXXXX,University of XXXX,"Choose one or more (Magnetosphere, ITM, Solar ...",2026-06-16 14:28:07,C:\Users\shoffma5\Box\HESTO\HTIDeS\21-HTIDS\21...,Yes
29,29,C:\Users\shoffma5\Box\HESTO\HTIDeS\20-HTIDS\20...,20-HTIDS20-0034,2026-07-27,2020,Hong Zhao,Auburn University,Magnetosphere,2026-06-16 11:43:10,C:\Users\shoffma5\Box\HESTO\HTIDeS\20-HTIDS\20...,Yes
30,30,C:\Users\shoffma5\Box\HESTO\HTIDeS\20-HTIDS\20...,"20-HTIDS20-0027, NASA 80NSSC21K0803",2026-07-27,2020,Chad Fish,Southwest Research Institute (SwRI) & Orion Sp...,Instrument Development,2026-06-16 13:27:05,C:\Users\shoffma5\Box\HESTO\HTIDeS\20-HTIDS\20...,Yes
31,31,C:\Users\shoffma5\Box\HESTO\HTIDeS\20-HTIDS\20...,20-HTIDS20-0009,2026-07-27,2020,Ian Cohen,JHU Applied Physics Laboratory,Interdisciplinary,2026-06-16 11:22:27,C:\Users\shoffma5\Box\HESTO\HTIDeS\20-HTIDS\20...,Yes
32,32,C:\Users\shoffma5\Box\HESTO\HTIDeS\20-HTIDS\20...,20-HTIDS20-0010,2026-04-15,2020,John W. Bonnell,Space Sciences Laboratory University of Califo...,"Magnetosphere, ITM, Heliosphere.",2026-05-04 18:51:59,C:\Users\shoffma5\Box\HESTO\HTIDeS\20-HTIDS\20...,Yes
33,33,C:\Users\shoffma5\Box\HESTO\HTIDeS\20-HTIDS\20...,20-HTIDS20-0028,2026-07-27,2020,Dr. Sona Hosseini,JPL-Caltech,Heliosphere,2026-06-16 13:53:56,C:\Users\shoffma5\Box\HESTO\HTIDeS\20-HTIDS\20...,Yes
34,34,C:\Users\shoffma5\Box\HESTO\HTIDeS\19-HTIDS\19...,19-HTIDS19-0027,2026-07-15,2019,Sam Yee,"Applied Physics Laboratory, Johns Hopkins Univ...",Ionosphere-Thermosphere-Mesosphere,2026-06-17 11:14:20,C:\Users\shoffma5\Box\HESTO\HTIDeS\19-HTIDS\19...,Yes
35,35,C:\Users\shoffma5\Box\HESTO\HFOS\24-HFOS\24-HF...,24-HFOS24-0013,2026-04-29,2024,Greg Holsclaw,University of Colorado,Ionosphere-Thermosphere-Mesosphere (ITM),2026-04-29 18:57:30,C:\Users\shoffma5\Box\HESTO\HFOS\24-HFOS\24-HF...,Yes
36,36,C:\Users\shoffma5\Box\HESTO\HFOS\24-HFOS\24-HF...,24-HFOS24-0008,2026-04-24,2024,Dr. Christopher S. Moore,Harvard-Smithsonian Center for Astrophysics,Solar Science and Space Weather,2026-04-26 23:07:41,C:\Users\shoffma5\Box\HESTO\HFOS\24-HFOS\24-HF...,Yes
37,37,C:\Users\shoffma5\Box\HESTO\HFOS\23-HFOS\23-HF...,23-HFOS23-0003,2026-04-26,2023,Hong Zhao,Auburn University,Magnetosphere,2026-04-26 09:33:58,C:\Users\shoffma5\Box\HESTO\HFOS\23-HFOS\23-HF...,Yes
38,38,C:\Users\shoffma5\Box\HESTO\HFOS\20-HFOS\20-HF...,20-HFOS20-0011,2026-04-15,2020,Wendy Frank,NaN,NaN,2026-05-05 10:15:40,C:\Users\shoffma5\Box\HESTO\HFOS\20-HFOS\20-HF...,Yes
39,39,C:\Users\shoffma5\Box\HESTO\Special Projects\2...,22-PROJ-0001,2026-05-15,2020,David Miles,None,None,2026-05-10 08:29:53,C:\Users\shoffma5\Box\HESTO\Special Projects\2...,Yes
40,40,C:\Users\shoffma5\Box\HESTO\Special Projects\1...,18-HTIDS18-0010,2026-05-15,2018,David Miles,None,None,2026-05-10 08:55:00,C:\Users\shoffma5\Box\HESTO\Special Projects\1...,Yes

## Export report sub-tables
Each sub-table (publications, patents, student metrics, project status) is
written to its own CSV in **long format** — one row per item, with `project_id`
as the repeating link key back to `report_files.csv`. Only **active** reports
are included. Headers are normalized to clean names by column position.

In [47]:
# Sub-table / master-table export logic lives in hestodb.export
from hestodb.export import (
    build_detail_csv,
    build_master_table,
    group_for,
    PUBLICATION_COLS,
    PATENT_COLS,
    STUDENT_COLS,
    STATUS_COLS,
)

In [48]:
publications = build_detail_csv(
    reports, files, "publication_table", PUBLICATION_COLS, "publications.csv"
)
print(
    f"publications.csv: {len(publications)} rows "
    f"({publications['project_id'].nunique()} projects)"
)
publications.head()

publications.csv: 202 rows (40 projects)

,project_id,publication_type,title,publication_date,publisher_name,url
0,24-HTIDS24-0036,Peer-reviewed journal,,N/A,,
1,24-HTIDS24-0036,Non-peer-reviewed journal,,N/A,,
2,24-HTIDS24-0036,Conference presentation (oral),,N/A,,
3,24-HTIDS24-0036,Conference presentation (poster),,N/A,,
4,24-HTIDS24-0036,Web article,,https://lasp.colorado.edu/2026/04/21/nasa-sele...,,

In [49]:
patents = build_detail_csv(reports, files, "patents_table", PATENT_COLS, "patents.csv")
print(f"patents.csv: {len(patents)} rows ({patents['project_id'].nunique()} projects)")
patents.head()

patents.csv: 34 rows (10 projects)

,project_id,patent_type,patent_name,patent_number,patent_date,resource_link
0,24-HTIDS24-0005,,SONTRAC is under review for a patent,,,
1,23-HTIDS23-0001,Patent,HYBRID AC/DC MAGNETOMETER WITH ATTITUDE DETERM...,"Moldwin, Ojeda, Cutler","U.S. Provisional Application No.: 63/635,058;",2024
2,23-HTIDS23-0001,Patent,Wavelet-Adaptive Interference Cancellation For...,Hoffmann and Moldwin,"U.S. Provision Application No.: US18/768,522 U...",2025-01-16
3,23-HTIDS23-0004,Peer-reviewed journal,,,,
4,23-HTIDS23-0004,Non-peer-reviewed journal,,,,

In [50]:
student_metrics = build_detail_csv(
    reports, files, "student_metrics_table", STUDENT_COLS, "student_metrics.csv"
)
print(
    f"student_metrics.csv: {len(student_metrics)} rows "
    f"({student_metrics['project_id'].nunique()} projects)"
)
student_metrics.head()

student_metrics.csv: 33 rows (13 projects)

,project_id,student_name,major,affiliation,level
0,24-HTIDS24-0036,Kai Pesce (to be hired in May),Mechanical Engineering,CU Boulder,Undergrad
1,24-HTIDS24-0025 (80NSSC25K7661),Roy Valdez,Mechanical Engineering (Graduation: May 2026),University of Texas in San Antonio,Undergrad
2,24-HTIDS24-0025 (80NSSC25K7661),Jasmine Arce,Electrical Engineering (Graduation: May 2027),Arizona State University,Undergrad
3,24-HTIDS24-0025 (80NSSC25K7661),Carlos Giai,Space Physics (Graduation: May 2028),University of Texas in San Antonio,Graduate
4,24-HTIDS24-0022,Oasis Aguayo,Physics,"School of Physics and Astronomy, Univ. MN",PhD student (1st year)

In [51]:
project_status = build_detail_csv(
    reports, files, "project_status", STATUS_COLS, "project_status.csv"
)
print(
    f"project_status.csv: {len(project_status)} rows "
    f"({project_status['project_id'].nunique()} projects)"
)
project_status.head()

project_status.csv: 180 rows (29 projects)

,project_id,category,prior,current,rationale
0,24-HTIDS24-0036,cost,n/a,g,"Discuss any issues with spending your funding,..."
1,24-HTIDS24-0036,schedule,n/a,g,Noteworthy changes in your original developmen...
2,24-HTIDS24-0036,technical,n/a,g,Summary of technical accomplishments or setbac...
3,24-HTIDS24-0036,staffing,n/a,g,"Noteworthy developments with PI, Co-I or other..."
4,24-HTIDS24-0036,facilities,n/a,g,Summary of any facility or lab related develop...

## Master table (one row per active report)
Folds all six slide parsers into a single table (one row per active report):
- **summary** + **accommodation** columns come straight from `files`
- **project_status** is pivoted to fixed `{category}_prior / _current / _rationale` columns
- **publications / patents / student_metrics** contribute a count (`n_*`) plus a `" ;; "`-joined detail column (full detail lives in the per-table CSVs above)

In [52]:
master = build_master_table(reports, files, "master_table.csv")
print(
    f"master_table.csv: {len(master)} rows, {master.shape[1]} columns "
    "(grouped 2-row header)"
)
print("read back with:  pd.read_csv('master_table.csv', header=[0, 1])")

# preview using the grouped header
master_preview = master.copy()
master_preview.columns = pd.MultiIndex.from_tuples(
    [(group_for(c), c) for c in master.columns]
)
master_preview.head()

master_table.csv: 41 rows, 50 columns (grouped 2-row header)
read back with:  pd.read_csv('master_table.csv', header=[0, 1])

                                            metadata                    \
                                           file_path report_date  year
0  C:\Users\shoffma5\Box\HESTO\HTIDeS\24-HTIDS\24...  2026-04-04  2024
1  C:\Users\shoffma5\Box\HESTO\HTIDeS\24-HTIDS\24...  2026-04-26  2024
2  C:\Users\shoffma5\Box\HESTO\HTIDeS\24-HTIDS\24...  2026-04-30  2024
3  C:\Users\shoffma5\Box\HESTO\HTIDeS\24-HTIDS\24...  2026-05-11  2024
4  C:\Users\shoffma5\Box\HESTO\HTIDeS\24-HTIDS\24...  2026-05-15  2024

                                                                          \
             modified                                             folder
0 2026-06-15 15:12:48  C:\Users\shoffma5\Box\HESTO\HTIDeS\24-HTIDS\24...
1 2026-04-26 16:14:23  C:\Users\shoffma5\Box\HESTO\HTIDeS\24-HTIDS\24...
2 2026-06-16 14:51:28  C:\Users\shoffma5\Box\HESTO\HTIDeS\24-HTIDS\24...
3 2026-06-10 10:51:52  C:\Users\shoffma5\Box\HESTO\HTIDeS\24-HTIDS\24...
4 2026-06-09 15:58:16  C:\Users\shoffma5\Box\HESTO\HTIDeS\24-HTIDS\24...

                                     summary                         \
  is_active                       project_id principal_investigator
0       Yes                  24-HTIDS24-0036          Maria Usanova
1       Yes  24-HTIDS24-0025 (80NSSC25K7661)      Gregory P. Miller
2       Yes                  24-HTIDS24-0006            Shawn Liang
3       Yes                  24-HTIDS24-0022       Lindsay Glesener
4       Yes                  24-HTIDS24-0039      Dhirendra Kataria

                                                      \
                                         affiliation
0                     University of Colorado Boulder
1      Southwest Research Institute, San Antonio, TX
2  Johns Hopkins University Applied Physics Labor...
3                            University of Minnesota
4          Southwest Research Institute, San Antonio

                                                      ...    project_status  \
                                     research_regime  ... technical_current
0                                      Magnetosphere  ...                 g
1                                 Magnetosphere, ITM  ...               NaN
2  Magnetosphere, Solar Science, Heliosphere, Spa...  ...                 g
3          Solar Science, Heliosphere, Space Weather  ...               NaN
4                                      Magnetosphere  ...               NaN

                                                                     \
                                 technical_rationale staffing_prior
0  Summary of technical accomplishments or setbac...            n/a
1                                                NaN            NaN
2  Summary of technical accomplishments or setbac...              g
3                                                NaN            NaN
4                                                NaN            NaN

                                                                       \
  staffing_current                                 staffing_rationale
0                g  Noteworthy developments with PI, Co-I or other...
1              NaN                                                NaN
2                g  Well staff. If we pursue the VLEO chamber test...
3              NaN                                                NaN
4              NaN                                                NaN

                                       \
  facilities_prior facilities_current
0              n/a                  g
1              NaN                NaN
2                y                  y
3              NaN                NaN
4              NaN                NaN

                                                     student_metrics  \
                                facilities_rationale      n_students
0  Summary of any facility or lab related develop...               1
1                                                NaN               3
2  Multiple particles instruments (NOAA SWiPS, NO...               0
3                                                NaN               4
4                                                NaN               0


                                     students_detail
0  Kai Pesce (to be hired in May) | Mechanical En...
1  Roy Valdez | Mechanical Engineering (Graduatio...
2
3  Oasis Aguayo | Physics | School of Physics and...
4

[5 rows x 50 columns]

## Smith test-file verification table
Collects **everything** parsed from the Smith test file (`test_report`) into one
tidy long-format dataframe so each parsed value can be checked against the source
slides. Columns: `section | row | field | value`. Scalar header fields and the
summary dict live on `row 0`; each parsed table contributes one row per
(record, column) cell.

In [53]:
# Build one tidy long-format table of everything parsed from the Smith test file.
verify_rows = []


def _add_scalar(section, field, value):
    verify_rows.append({"section": section, "row": 0, "field": field, "value": value})


def _add_frame(section, df):
    if df is None or len(df) == 0:
        return
    df = df.reset_index(drop=True)
    for i, record in df.iterrows():
        for col in df.columns:
            verify_rows.append(
                {
                    "section": section,
                    "row": i,
                    "field": str(col),
                    "value": record[col],
                }
            )


# scalar header fields
_add_scalar("metadata", "project_id", test_report.project_id)
_add_scalar("metadata", "principal_investigator", test_report.principal_investigator)
_add_scalar("metadata", "affiliation", test_report.affiliation)
_add_scalar("metadata", "research_regime", test_report.research_regime)

# summary dict (one field per key)
for key, value in (test_report.summary or {}).items():
    _add_scalar("summary", key, value)

# parsed tables (one row per cell)
_add_frame("accommodation", test_report.accomodation_table)
_add_frame("publications", test_report.publication_table)
_add_frame("patents", test_report.patents_table)
_add_frame("student_metrics", test_report.student_metrics_table)
_add_frame("project_status", test_report.project_status)

smith_verify = pd.DataFrame(verify_rows, columns=["section", "row", "field", "value"])
print(
    f"smith_verify: {len(smith_verify)} parsed values across "
    f"{smith_verify['section'].nunique()} sections "
    f"({', '.join(smith_verify['section'].unique())})"
)

# show every row so values can be eyeballed against the slides
with pd.option_context("display.max_rows", None, "display.max_colwidth", None):
    display(smith_verify)

smith_verify: 103 parsed values across 7 sections (metadata, summary, accommodation, publications, patents, student_metrics, project_status)

,section,row,field,value
0,metadata,0,project_id,24-HTIDS24-0009
1,metadata,0,principal_investigator,Jane Smith
2,metadata,0,affiliation,NASA Goddard Space Flight Center
3,metadata,0,research_regime,heliosphere
4,summary,0,date,2026-12-10
5,summary,0,proposal title,A project to develop a new x-ray detector
6,summary,0,technology name (acronym),AWESOME
7,summary,0,principal investigator,Jane Smith
8,summary,0,pi email,Jane.smith@fakeemail.org
9,summary,0,affiliation,NASA Goddard Space Flight Center
10,summary,0,proposal id,24-HTIDS24-0009
11,summary,0,research regime,heliosphere
12,summary,0,hesto taxonomy,Photons – X-rays
13,summary,0,instrument type(s),Spectrometer
14,summary,0,technology keyword,Quantum Sensing
15,summary,0,project summary (two to three sentences),This is a project to develop a new x-ray detector. This is the second sentence. This is the third sentence.
16,summary,0,techport url,https://techport.nasa.gov/projects/95780
17,accommodation,0,category,payload size
18,accommodation,0,sub_category,length
19,accommodation,0,value,10.0
20,accommodation,1,category,payload size
21,accommodation,1,sub_category,width
22,accommodation,1,value,10.0
23,accommodation,2,category,payload size
24,accommodation,2,sub_category,height
25,accommodation,2,value,10.0
26,accommodation,3,category,payload volume
27,accommodation,3,sub_category,
28,accommodation,3,value,1.0
29,accommodation,4,category,power requirements
30,accommodation,4,sub_category,average
31,accommodation,4,value,5.0
32,accommodation,5,category,power requirements
33,accommodation,5,sub_category,peak
34,accommodation,5,value,10.0
35,accommodation,6,category,mass
36,accommodation,6,sub_category,
37,accommodation,6,value,5.4
38,accommodation,7,category,pointing requirements
39,accommodation,7,sub_category,arcsecs
40,accommodation,7,value,60.0
41,accommodation,8,category,pointing requirements
42,accommodation,8,sub_category,arcminutes
43,accommodation,8,value,1.0
44,accommodation,9,category,data rate
45,accommodation,9,sub_category,average
46,accommodation,9,value,15.0
47,accommodation,10,category,data rate
48,accommodation,10,sub_category,peak
49,accommodation,10,value,100.0
50,accommodation,11,category,power interface port
51,accommodation,11,sub_category,
52,accommodation,11,value,"db-9, 28 v, 1a"
53,accommodation,12,category,communication interface protocol
54,accommodation,12,sub_category,
55,accommodation,12,value,uart
56,accommodation,13,category,data communication port
57,accommodation,13,sub_category,
58,accommodation,13,value,db-9
59,accommodation,14,category,requires thermal isolation
60,accommodation,14,sub_category,
61,accommodation,14,value,false
62,accommodation,15,category,special power considerations
63,accommodation,15,sub_category,
64,accommodation,15,value,none
65,publications,0,Type choose one of below,Conference presentation (oral)
66,publications,0,Title,Development of the Next-Generation Solar X-ray detector
67,publications,0,Publication/Presentation Date,23-Jan-2026
68,publications,0,Publisher/Conference Name,IEEE NSS/MIC
69,publications,0,URL,https://ieeexplore.ieee.org/document/10657175
70,patents,0,"Type (Issued, Filing)",Issued
71,patents,0,Name,Art of transmitting electrical energy through the natural mediums
72,patents,0,Patent or License Number,US787412A
73,patents,0,Date,1900-05-16
74,patents,0,"Resource Link (e.g., Google Patents Link)",https://patents.google.com/patent/US787412A/
75,student_metrics,0,Student Name (first last),John Doe
76,student_metrics,0,Major,Physics
77,student_metrics,0,"Affiliation (School, University, etc.)",University of Alabama
78,student_metrics,0,"Level (High School, Undergrad, Grad, PhD)",Undergrad
79,project_status,0,category,cost
80,project_status,0,prior,y
81,project_status,0,current,y
82,project_status,0,rationale,"Discuss any issues with spending your funding, needs for augmentation, etc."
83,project_status,1,category,schedule
84,project_status,1,prior,g
85,project_status,1,current,g
86,project_status,1,rationale,"Noteworthy changes in your original development schedule. If behind schedule, indicate number of months behind."
87,project_status,2,category,technical
88,project_status,2,prior,g
89,project_status,2,current,g
90,project_status,2,rationale,Summary of technical accomplishments or setbacks experienced since last report.
91,project_status,3,category,staffing
92,project_status,3,prior,g
93,project_status,3,current,g
94,project_status,3,rationale,"Noteworthy developments with PI, Co-I or other personnel working on award during this period."
95,project_status,4,category,facilities
96,project_status,4,prior,g
97,project_status,4,current,g
98,project_status,4,rationale,Summary of any facility or lab related developments.
99,project_status,5,category,overall
100,project_status,5,prior,y
101,project_status,5,current,y
102,project_status,5,rationale,Overall assessment of progress or lack thereof during the quarter.

In [54]:
files[files["year"] == 2024]

,index,file_path,project_id,report_date,year,principal_investigator,affiliation,research_regime,modified,folder,is_active
0,0,C:\Users\shoffma5\Box\HESTO\HTIDeS\24-HTIDS\24...,24-HTIDS24-0036,2026-04-04,2024,Maria Usanova,University of Colorado Boulder,Magnetosphere,2026-06-15 15:12:48,C:\Users\shoffma5\Box\HESTO\HTIDeS\24-HTIDS\24...,Yes
1,1,C:\Users\shoffma5\Box\HESTO\HTIDeS\24-HTIDS\24...,24-HTIDS24-0025 (80NSSC25K7661),2026-04-26,2024,Gregory P. Miller,"Southwest Research Institute, San Antonio, TX","Magnetosphere, ITM",2026-04-26 16:14:23,C:\Users\shoffma5\Box\HESTO\HTIDeS\24-HTIDS\24...,Yes
2,2,C:\Users\shoffma5\Box\HESTO\HTIDeS\24-HTIDS\24...,24-HTIDS24-0006,2026-04-30,2024,Shawn Liang,Johns Hopkins University Applied Physics Labor...,"Magnetosphere, Solar Science, Heliosphere, Spa...",2026-06-16 14:51:28,C:\Users\shoffma5\Box\HESTO\HTIDeS\24-HTIDS\24...,Yes
3,3,C:\Users\shoffma5\Box\HESTO\HTIDeS\24-HTIDS\24...,24-HTIDS24-0022,2026-05-11,2024,Lindsay Glesener,University of Minnesota,"Solar Science, Heliosphere, Space Weather",2026-06-10 10:51:52,C:\Users\shoffma5\Box\HESTO\HTIDeS\24-HTIDS\24...,Yes
4,4,C:\Users\shoffma5\Box\HESTO\HTIDeS\24-HTIDS\24...,24-HTIDS24-0039,2026-05-15,2024,Dhirendra Kataria,"Southwest Research Institute, San Antonio",Magnetosphere,2026-06-09 15:58:16,C:\Users\shoffma5\Box\HESTO\HTIDeS\24-HTIDS\24...,Yes
5,5,C:\Users\shoffma5\Box\HESTO\HTIDeS\24-HTIDS\24...,24-HTIDS24-0005,2026-05-15,2024,Georgia de Nolfo,NASA Goddard Space Flight Center,"Solar Science, Heliosphere, Space Weather",2026-04-26 13:47:32,C:\Users\shoffma5\Box\HESTO\HTIDeS\24-HTIDS\24...,Yes
35,35,C:\Users\shoffma5\Box\HESTO\HFOS\24-HFOS\24-HF...,24-HFOS24-0013,2026-04-29,2024,Greg Holsclaw,University of Colorado,Ionosphere-Thermosphere-Mesosphere (ITM),2026-04-29 18:57:30,C:\Users\shoffma5\Box\HESTO\HFOS\24-HFOS\24-HF...,Yes
36,36,C:\Users\shoffma5\Box\HESTO\HFOS\24-HFOS\24-HF...,24-HFOS24-0008,2026-04-24,2024,Dr. Christopher S. Moore,Harvard-Smithsonian Center for Astrophysics,Solar Science and Space Weather,2026-04-26 23:07:41,C:\Users\shoffma5\Box\HESTO\HFOS\24-HFOS\24-HF...,Yes

In [55]:
test_file = files[files["year"] == 2024].iloc[0]["file_path"]

In [56]:
this_report = Report(test_file)

HESTO-202604_Report_24-HTIDS-0036_Usanova-rev3.pptx: status category 'cost' has invalid prior value 'n/a'. Expected one of: ['g', 'y', 'r', 'green', 'yellow', 'red']
HESTO-202604_Report_24-HTIDS-0036_Usanova-rev3.pptx: status category 'schedule' has invalid prior value 'n/a'. Expected one of: ['g', 'y', 'r', 'green', 'yellow', 'red']
HESTO-202604_Report_24-HTIDS-0036_Usanova-rev3.pptx: status category 'technical' has invalid prior value 'n/a'. Expected one of: ['g', 'y', 'r', 'green', 'yellow', 'red']
HESTO-202604_Report_24-HTIDS-0036_Usanova-rev3.pptx: status category 'staffing' has invalid prior value 'n/a'. Expected one of: ['g', 'y', 'r', 'green', 'yellow', 'red']
HESTO-202604_Report_24-HTIDS-0036_Usanova-rev3.pptx: status category 'facilities' has invalid prior value 'n/a'. Expected one of: ['g', 'y', 'r', 'green', 'yellow', 'red']
HESTO-202604_Report_24-HTIDS-0036_Usanova-rev3.pptx: status category 'overall' has invalid prior value 'n/a'. Expected one of: ['g', 'y', 'r', 'green', 'yellow', 'red']
HESTO-202604_Report_24-HTIDS-0036_Usanova-rev3.pptx: unrecognised publication type 'Peer-reviewed journal'. Expected one of: ['Peer-reviewed publication', 'Non-Peer-reviewed publication', 'Conference presentation (oral)', 'Conference presentation (poster)', 'Web article']
HESTO-202604_Report_24-HTIDS-0036_Usanova-rev3.pptx: unrecognised publication type 'Non-peer-reviewed journal'. Expected one of: ['Peer-reviewed publication', 'Non-Peer-reviewed publication', 'Conference presentation (oral)', 'Conference presentation (poster)', 'Web article']

In [57]:
this_report

Report HESTO-202604_Report_24-HTIDS-0036_Usanova-rev3.pptx (37 slides)
Project ID: 24-HTIDS24-0036, PI: Maria Usanova

Category    Prior    Current
----------  -------  -------
overall     N/A      G
cost        N/A      G
schedule    N/A      G
technical   N/A      G
staffing    N/A      G
facilities  N/A      G

Accommodation:
Category                          Sub-category  Value
--------------------------------  ----------  ----
payload size                      length      6.0
                                  width       6.0
                                  height      6.0
payload volume                                1.0
power requirements                average     1.0
                                  peak        tbd
mass                                          tbd
pointing requirements             arcsecs     tbd
                                  arcminutes  tbd
data rate                         average     tbd
                                  peak        tbd
power interface port                          tbd
communication interface protocol              tbd
data communication port                       tbd
requires thermal isolation                    true
special power considerations                  none

Publications:
        Type choose one of below Title                                                              Publication/Presentation Date Publisher/Conference Name URL
           Peer-reviewed journal                                                                                              N/A
       Non-peer-reviewed journal                                                                                              N/A
  Conference presentation (oral)                                                                                              N/A
Conference presentation (poster)                                                                                              N/A
                     Web article       https://lasp.colorado.edu/2026/04/21/nasa-selects-cu-magnetometer-for-further-development/

In [58]:
this_report.accomodation_table

                            category sub_category value
0                       payload size       length   6.0
1                       payload size        width   6.0
2                       payload size       height   6.0
3                     payload volume                1.0
4                 power requirements      average   1.0
5                 power requirements         peak   tbd
6                               mass                tbd
7              pointing requirements      arcsecs   tbd
8              pointing requirements   arcminutes   tbd
9                          data rate      average   tbd
10                         data rate         peak   tbd
11              power interface port                tbd
12  communication interface protocol                tbd
13           data communication port                tbd
14        requires thermal isolation               true
15      special power considerations               none

In [59]:
this_report.publication_table

,Type choose one of below,Title,Publication/Presentation Date,Publisher/Conference Name,URL
0,Peer-reviewed journal,,N/A,,
1,Non-peer-reviewed journal,,N/A,,
2,Conference presentation (oral),,N/A,,
3,Conference presentation (poster),,N/A,,
4,Web article,,https://lasp.colorado.edu/2026/04/21/nasa-sele...,,

In [60]:
this_report.project_status

     category prior current                                          rationale
0        cost   n/a       g  Discuss any issues with spending your funding,...
1    schedule   n/a       g  Noteworthy changes in your original developmen...
2   technical   n/a       g  Summary of technical accomplishments or setbac...
3    staffing   n/a       g  Noteworthy developments with PI, Co-I or other...
4  facilities   n/a       g  Summary of any facility or lab related develop...
5     overall   n/a       g  Overall assessment of progress or lack thereof...

In [61]:
this_report.patents_table

In [62]:
test_file = files[files["year"] == 2024].iloc[1]["file_path"]
test_file

WindowsPath('C:/Users/shoffma5/Box/HESTO/HTIDeS/24-HTIDS/24-HTIDS24-0025 Gregory Miller/Reports/HESTO/HESTO-202604_Report_24-HTIDS24-0025_Miller-rev3_Apr26_2026.pptx')

In [63]:
this_report = Report(test_file)

HESTO-202604_Report_24-HTIDS24-0025_Miller-rev3_Apr26_2026.pptx: unrecognised publication type 'Peer-reviewed journal'. Expected one of: ['Peer-reviewed publication', 'Non-Peer-reviewed publication', 'Conference presentation (oral)', 'Conference presentation (poster)', 'Web article']
HESTO-202604_Report_24-HTIDS24-0025_Miller-rev3_Apr26_2026.pptx: unrecognised publication type 'Non-peer-reviewed journal'. Expected one of: ['Peer-reviewed publication', 'Non-Peer-reviewed publication', 'Conference presentation (oral)', 'Conference presentation (poster)', 'Web article']

In [64]:
this_report.accomodation_table

                            category sub_category                   value
0                       payload size       length                    10.0
1                       payload size        width                    10.0
2                       payload size       height                    30.0
3                     payload volume                                  3.0
4                 power requirements      average                     5.0
5                 power requirements         peak                     6.0
6                               mass                                  5.0
7              pointing requirements      arcsecs                     tbd
8              pointing requirements   arcminutes                     tbd
9                          data rate      average                    50.0
10                         data rate         peak                     tbd
11              power interface port               mdm-9, +14 v dc, tbd a
12  communication interface protocol                                rs422
13           data communication port                                mdm-9
14        requires thermal isolation                                false
15      special power considerations                                 none

In [65]:
this_report.summary

{'date': 'April 26, 2026',
 'proposal title': 'Development of next-generation compact time-of-flight plasma instruments for heliophysics exploration',
 'technology name (acronym)': 'N-TOF',
 'principal investigator': 'Gregory P. Miller',
 'pi email': 'gregory.miller@swri.org',
 'affiliation': 'Southwest Research Institute, San Antonio, TX',
 'proposal id': '24-HTIDS24-0025 (80NSSC25K7661)',
 'research regime': 'Magnetosphere, ITM',
 'hesto taxonomy': 'Ions/Protons, Electrons',
 'instrument type(s)': 'Ion and Electron Spectrometer (Top hat ESA w/ TOF)',
 'technology keyword': 'N/A',
 'project summary (two to three sentences)': 'A compact top hat ESA, TOF-based ion spectrometer that replaces carbon foils with MPOs and graphene foils, elevating the technology to TRL 6 for future flight opportunities, to study ions and electrons across various space plasma environments.',
 'techport url': 'N/A'}