# Hesto Notebook (uv environment)
This notebook is configured to use the workspace Python environment managed by uv (.venv).

In [1]:
import sys
import pandas as pd
from pathlib import Path

print(sys.executable)

c:\Users\shoffma5\Documents\GitHub_orig\hestodb\.venv\Scripts\python.exe

In [2]:
from hestodb.util import find_latest_report_pptx
from hestodb.report import Report
from hestodb import _test_report_pptx

print(_test_report_pptx)

c:\Users\shoffma5\Documents\GitHub_orig\hestodb\hestodb\data\test\HESTO-202612_Report_24-HTIDS24_Smith-rev3.pptx

Checking the test file

In [3]:
test_report = Report(_test_report_pptx)
print(test_report)

Report HESTO-202612_Report_24-HTIDS24_Smith-rev3.pptx (33 slides)
Project ID: 24-HTIDS24-0009, PI: Jane Smith

Category    Prior    Current
----------  -------  -------
overall     Y        Y
cost        Y        Y
schedule    G        G
technical   G        G
staffing    G        G
facilities  G        G

Accommodation:
Category                          Sub-category  Value
--------------------------------  ----------  --------------
payload size                      length      10.0
                                  width       10.0
                                  height      10.0
payload volume                                1.0
power requirements                average     5.0
                                  peak        10.0
mass                                          5.4
pointing requirements             arcsecs     60.0
                                  arcminutes  1.0
data rate                         average     15.0
                                  peak        100.0
power interface port                          db-9, 28 v, 1a
communication interface protocol              uart
data communication port                       db-9
requires thermal isolation                    false
special power considerations                  none

Publications:
      Type choose one of below                                                   Title Publication/Presentation Date Publisher/Conference Name                                           URL
Conference presentation (oral) Development of the Next-Generation Solar X-ray detector                   23-Jan-2026              IEEE NSS/MIC https://ieeexplore.ieee.org/document/10657175

In [4]:
test_report.accomodation_table

                            category sub_category           value
0                       payload size       length            10.0
1                       payload size        width            10.0
2                       payload size       height            10.0
3                     payload volume                          1.0
4                 power requirements      average             5.0
5                 power requirements         peak            10.0
6                               mass                          5.4
7              pointing requirements      arcsecs            60.0
8              pointing requirements   arcminutes             1.0
9                          data rate      average            15.0
10                         data rate         peak           100.0
11              power interface port               db-9, 28 v, 1a
12  communication interface protocol                         uart
13           data communication port                         db-9
14        requires thermal isolation                        false
15      special power considerations                         none

In [5]:
test_report.publication_table

,Type choose one of below,Title,Publication/Presentation Date,Publisher/Conference Name,URL
0,Conference presentation (oral),Development of the Next-Generation Solar X-ray...,23-Jan-2026,IEEE NSS/MIC,https://ieeexplore.ieee.org/document/10657175

In [6]:
test_report.patents_table

,"Type (Issued, Filing)",Name,Patent or License Number,Date,"Resource Link (e.g., Google Patents Link)"
0,Issued,Art of transmitting electrical energy through ...,US787412A,1900-05-16,https://patents.google.com/patent/US787412A/

In [7]:
test_report.student_metrics_table

,Student Name (first last),Major,"Affiliation (School, University, etc.)","Level (High School, Undergrad, Grad, PhD)"
0,John Doe,Physics,University of Alabama,Undergrad

In [ ]:
files = [
    find_latest_report_pptx(Path("C:\\Users\\shoffma5\\Box\\HESTO\\HTIDeS")),
    find_latest_report_pptx(Path("C:\\Users\\shoffma5\\Box\\HESTO\\HFOS")),
    find_latest_report_pptx(Path("C:\\Users\\shoffma5\\Box\\HESTO\\Special Projects")),
]
files = pd.concat(files, ignore_index=True)
reports = [Report(p) for p in files["file_path"]]
print(f"Found {len(reports)} report files:")
files.to_csv("report_files.csv", index=False)
files

In [ ]:
frames = []


def add_table(df, label):
    if df is not None:
        df = df.copy()
        df["table"] = label
        frames.append(df)


add_table(test_report.student_metrics_table, "student_metrics")
add_table(test_report.accomodation_table, "accomodation")
add_table(test_report.publication_table, "publications")
add_table(test_report.patents_table, "patents")
add_table(test_report.project_status, "project_status")

combined = pd.concat(frames, ignore_index=True)
combined

,Student Name (first last),Major,"Affiliation (School, University, etc.)","Level (High School, Undergrad, Grad, PhD)",table,category,sub_category,value,Type choose one of below,Title,Publication/Presentation Date,Publisher/Conference Name,URL,"Type (Issued, Filing)",Name,Patent or License Number,Date,"Resource Link (e.g., Google Patents Link)",prior,current
0,John Doe,Physics,University of Alabama,Undergrad,student_metrics,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,accomodation,payload size,length,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,accomodation,payload size,width,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,accomodation,payload size,height,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,accomodation,payload volume,,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,accomodation,power requirements,average,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,accomodation,power requirements,peak,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,accomodation,mass,,5.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,accomodation,pointing requirements,arcsecs,60.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,accomodation,pointing requirements,arcminutes,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,NaN,NaN,NaN,accomodation,data rate,average,15.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,NaN,NaN,NaN,accomodation,data rate,peak,100.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,NaN,NaN,NaN,NaN,accomodation,power interface port,,"db-9, 28 v, 1a",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,NaN,NaN,NaN,NaN,accomodation,communication interface protocol,,uart,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,NaN,NaN,NaN,NaN,accomodation,data communication port,,db-9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,NaN,NaN,NaN,NaN,accomodation,requires thermal isolation,,false,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,NaN,NaN,NaN,NaN,accomodation,special power considerations,,none,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,NaN,NaN,NaN,NaN,publications,NaN,NaN,NaN,Conference presentation (oral),Development of the Next-Generation Solar X-ray...,23-Jan-2026,IEEE NSS/MIC,https://ieeexplore.ieee.org/document/10657175,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,NaN,NaN,NaN,NaN,patents,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Issued,Art of transmitting electrical energy through ...,US787412A,1900-05-16,https://patents.google.com/patent/US787412A/,NaN,NaN
19,NaN,NaN,NaN,NaN,project_status,cost,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,y,y
20,NaN,NaN,NaN,NaN,project_status,schedule,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,g,g
21,NaN,NaN,NaN,NaN,project_status,technical,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,g,g
22,NaN,NaN,NaN,NaN,project_status,staffing,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,g,g
23,NaN,NaN,NaN,NaN,project_status,facilities,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,g,g
24,NaN,NaN,NaN,NaN,project_status,overall,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,y,y

In [ ]:
files[files["year"] == 2024]

,file_path,project_id,report_date,year,principal_investigator,affiliation,research_regime,modified,folder,length,...,attitude_knowledge,attitude_control,average_data_rate,peak_data_rate,power_interface_port,communication_interface_protocol,data_connector_type,thermal_isolation,circuit_protection,is_active
0,C:\Users\shoffma5\Box\HESTO\HTIDeS\24-HTIDS\24...,24-HTIDS24-0036,2026-04-04,2024,Maria Usanova,University of Colorado Boulder,Magnetosphere,2026-06-15 15:12:48,C:\Users\shoffma5\Box\HESTO\HTIDeS\24-HTIDS\24...,6.0,...,tbd,tbd,tbd,tbd,tbd,tbd,tbd,true,none,Yes
1,C:\Users\shoffma5\Box\HESTO\HTIDeS\24-HTIDS\24...,24-HTIDS24-0025 (80NSSC25K7661),2026-04-26,2024,Gregory P. Miller,"Southwest Research Institute, San Antonio, TX","Magnetosphere, ITM",2026-04-26 16:14:23,C:\Users\shoffma5\Box\HESTO\HTIDeS\24-HTIDS\24...,10.0,...,tbd,tbd,50.0,tbd,"mdm-9, +14 v dc, tbd a",rs422,mdm-9,false,none,Yes
2,C:\Users\shoffma5\Box\HESTO\HTIDeS\24-HTIDS\24...,24-HTIDS24-0006,2026-04-30,2024,Shawn Liang,Johns Hopkins University Applied Physics Labor...,"Magnetosphere, Solar Science, Heliosphere, Spa...",2026-06-15 15:47:03,C:\Users\shoffma5\Box\HESTO\HTIDeS\24-HTIDS\24...,15.0,...,not driving fov,6 degree fwhm,tbd,tbd,"mdm-9, 28vdc, 1a",uart – lvds,mdm-15,false,none,Yes
3,C:\Users\shoffma5\Box\HESTO\HTIDeS\24-HTIDS\24...,24-HTIDS24-0005,2026-04-15,2024,Georgia de Nolfo,NASA Goddard Space Flight Center,"Solar Science, Heliosphere, Space Weather",2026-04-26 13:47:32,C:\Users\shoffma5\Box\HESTO\HTIDeS\24-HTIDS\24...,10.0,...,60.0,1.0,15.0,100.0,"db-9, 28 v, 1a",uart,db-9,false,none,Yes
4,C:\Users\shoffma5\Box\HESTO\HTIDeS\24-HTIDS\24...,24-HTIDS24-0039,2026-05-15,2024,Dhirendra Kataria,"Southwest Research Institute, San Antonio",Magnetosphere,2026-06-09 15:58:16,C:\Users\shoffma5\Box\HESTO\HTIDeS\24-HTIDS\24...,None,...,None,None,None,None,,NaN,,,,Yes
5,C:\Users\shoffma5\Box\HESTO\HTIDeS\24-HTIDS\24...,24-HTIDS24-0022,2026-05-11,2024,Lindsay Glesener,University of Minnesota,"Solar Science, Heliosphere, Space Weather",2026-06-10 10:51:52,C:\Users\shoffma5\Box\HESTO\HTIDeS\24-HTIDS\24...,10.0,...,~1 deg abs. knowledge,sun-pointed.,None,None,d-sub 9-pin connector (tbr).,"uart (rs-422) or ethernet, tbd.",db-9 (tbr).,false,tbd,Yes
29,C:\Users\shoffma5\Box\HESTO\HFOS\24-HFOS\24-HF...,24-HFOS24-0013,2026-04-29,2024,Greg Holsclaw,University of Colorado,Ionosphere-Thermosphere-Mesosphere (ITM),2026-04-29 18:57:30,C:\Users\shoffma5\Box\HESTO\HFOS\24-HFOS\24-HF...,10.0,...,60.0,1.0,15.0,100.0,"db-9, 28 v, 1a",uart,db-9,false,none,Yes
30,C:\Users\shoffma5\Box\HESTO\HFOS\24-HFOS\24-HF...,24-HFOS24-0008,2026-04-24,2024,Dr. Christopher S. Moore,Harvard-Smithsonian Center for Astrophysics,Solar Science and Space Weather,2026-04-26 23:07:41,C:\Users\shoffma5\Box\HESTO\HFOS\24-HFOS\24-HF...,NaN,...,NaN,NaN,NaN,NaN,,NaN,,,,Yes

In [ ]:
test_file = files[files["year"] == 2024].iloc[0]["file_path"]

In [ ]:
this_report = Report(test_file)

HESTO-202604_Report_24-HTIDS-0036_Usanova-rev3.pptx: status category 'cost' has invalid prior value 'n/a'. Expected one of: ['g', 'y', 'r', 'green', 'yellow', 'red']
HESTO-202604_Report_24-HTIDS-0036_Usanova-rev3.pptx: status category 'schedule' has invalid prior value 'n/a'. Expected one of: ['g', 'y', 'r', 'green', 'yellow', 'red']
HESTO-202604_Report_24-HTIDS-0036_Usanova-rev3.pptx: status category 'technical' has invalid prior value 'n/a'. Expected one of: ['g', 'y', 'r', 'green', 'yellow', 'red']
HESTO-202604_Report_24-HTIDS-0036_Usanova-rev3.pptx: status category 'staffing' has invalid prior value 'n/a'. Expected one of: ['g', 'y', 'r', 'green', 'yellow', 'red']
HESTO-202604_Report_24-HTIDS-0036_Usanova-rev3.pptx: status category 'facilities' has invalid prior value 'n/a'. Expected one of: ['g', 'y', 'r', 'green', 'yellow', 'red']
HESTO-202604_Report_24-HTIDS-0036_Usanova-rev3.pptx: status category 'overall' has invalid prior value 'n/a'. Expected one of: ['g', 'y', 'r', 'green', 'yellow', 'red']
HESTO-202604_Report_24-HTIDS-0036_Usanova-rev3.pptx: unrecognised publication type 'Peer-reviewed journal'. Expected one of: ['Peer-reviewed publication', 'Non-Peer-reviewed publication', 'Conference presentation (oral)', 'Conference presentation (poster)', 'Web article']
HESTO-202604_Report_24-HTIDS-0036_Usanova-rev3.pptx: unrecognised publication type 'Non-peer-reviewed journal'. Expected one of: ['Peer-reviewed publication', 'Non-Peer-reviewed publication', 'Conference presentation (oral)', 'Conference presentation (poster)', 'Web article']

In [ ]:
this_report

Report HESTO-202604_Report_24-HTIDS-0036_Usanova-rev3.pptx (37 slides)
Project ID: 24-HTIDS24-0036, PI: Maria Usanova

Category    Prior    Current
----------  -------  -------
overall     N/A      G
cost        N/A      G
schedule    N/A      G
technical   N/A      G
staffing    N/A      G
facilities  N/A      G

Accommodation:
Category                          Sub-category  Value
--------------------------------  ----------  ----
payload size                      length      6.0
                                  width       6.0
                                  height      6.0
payload volume                                1.0
power requirements                average     1.0
                                  peak        tbd
mass                                          tbd
pointing requirements             arcsecs     tbd
                                  arcminutes  tbd
data rate                         average     tbd
                                  peak        tbd
power interface port                          tbd
communication interface protocol              tbd
data communication port                       tbd
requires thermal isolation                    true
special power considerations                  none

Publications:
        Type choose one of below Title                                                              Publication/Presentation Date Publisher/Conference Name URL
           Peer-reviewed journal                                                                                              N/A
       Non-peer-reviewed journal                                                                                              N/A
  Conference presentation (oral)                                                                                              N/A
Conference presentation (poster)                                                                                              N/A
                     Web article       https://lasp.colorado.edu/2026/04/21/nasa-selects-cu-magnetometer-for-further-development/

In [ ]:
this_report.accomodation_table

                            category sub_category value
0                       payload size       length   6.0
1                       payload size        width   6.0
2                       payload size       height   6.0
3                     payload volume                1.0
4                 power requirements      average   1.0
5                 power requirements         peak   tbd
6                               mass                tbd
7              pointing requirements      arcsecs   tbd
8              pointing requirements   arcminutes   tbd
9                          data rate      average   tbd
10                         data rate         peak   tbd
11              power interface port                tbd
12  communication interface protocol                tbd
13           data communication port                tbd
14        requires thermal isolation               true
15      special power considerations               none

In [ ]:
this_report.publication_table

,Type choose one of below,Title,Publication/Presentation Date,Publisher/Conference Name,URL
0,Peer-reviewed journal,,N/A,,
1,Non-peer-reviewed journal,,N/A,,
2,Conference presentation (oral),,N/A,,
3,Conference presentation (poster),,N/A,,
4,Web article,,https://lasp.colorado.edu/2026/04/21/nasa-sele...,,

In [ ]:
this_report.project_status

     category prior current
0        cost   n/a       g
1    schedule   n/a       g
2   technical   n/a       g
3    staffing   n/a       g
4  facilities   n/a       g
5     overall   n/a       g

In [ ]:
this_report.patents_table

In [ ]:
test_file = files[files["year"] == 2024].iloc[1]["file_path"]
test_file

WindowsPath('C:/Users/shoffma5/Box/HESTO/HTIDeS/24-HTIDS/24-HTIDS24-0025 Gregory Miller/Reports/HESTO/HESTO-202604_Report_24-HTIDS24-0025_Miller-rev3_Apr26_2026.pptx')

In [ ]:
this_report = Report(test_file)

HESTO-202604_Report_24-HTIDS24-0025_Miller-rev3_Apr26_2026.pptx: unrecognised publication type 'Peer-reviewed journal'. Expected one of: ['Peer-reviewed publication', 'Non-Peer-reviewed publication', 'Conference presentation (oral)', 'Conference presentation (poster)', 'Web article']
HESTO-202604_Report_24-HTIDS24-0025_Miller-rev3_Apr26_2026.pptx: unrecognised publication type 'Non-peer-reviewed journal'. Expected one of: ['Peer-reviewed publication', 'Non-Peer-reviewed publication', 'Conference presentation (oral)', 'Conference presentation (poster)', 'Web article']

In [ ]:
this_report.accomodation_table

                            category sub_category                   value
0                       payload size       length                    10.0
1                       payload size        width                    10.0
2                       payload size       height                    30.0
3                     payload volume                                  3.0
4                 power requirements      average                     5.0
5                 power requirements         peak                     6.0
6                               mass                                  5.0
7              pointing requirements      arcsecs                     tbd
8              pointing requirements   arcminutes                     tbd
9                          data rate      average                    50.0
10                         data rate         peak                     tbd
11              power interface port               mdm-9, +14 v dc, tbd a
12  communication interface protocol                                rs422
13           data communication port                                mdm-9
14        requires thermal isolation                                false
15      special power considerations                                 none

In [ ]:
this_report.summary

{'date': 'April 26, 2026',
 'proposal title': 'Development of next-generation compact time-of-flight plasma instruments for heliophysics exploration',
 'technology name (acronym)': 'N-TOF',
 'principal investigator': 'Gregory P. Miller',
 'pi email': 'gregory.miller@swri.org',
 'affiliation': 'Southwest Research Institute, San Antonio, TX',
 'proposal id': '24-HTIDS24-0025 (80NSSC25K7661)',
 'research regime': 'Magnetosphere, ITM',
 'hesto taxonomy': 'Ions/Protons, Electrons',
 'instrument type(s)': 'Ion and Electron Spectrometer (Top hat ESA w/ TOF)',
 'technology keyword': 'N/A',
 'project summary (two to three sentences)': 'A compact top hat ESA, TOF-based ion spectrometer that replaces carbon foils with MPOs and graphene foils, elevating the technology to TRL 6 for future flight opportunities, to study ions and electrons across various space plasma environments.',
 'techport url': 'N/A'}