# Hesto Notebook (uv environment)
This notebook is configured to use the workspace Python environment managed by uv (.venv).

In [95]:
import sys
import pandas as pd
from pathlib import Path
from datetime import datetime
print(sys.executable)

c:\Users\shoffma5\Documents\GitHub_orig\hestodb\.venv\Scripts\python.exe

In [96]:
from hestodb.util import parse_file_path, find_latest_report_pptx
from hestodb.report import Report
from hestodb import _test_report_pptx
print(_test_report_pptx)

c:\Users\shoffma5\Documents\GitHub_orig\hestodb\hestodb\data\test\HESTO-202612_Report_24-HTIDS24_Smith-rev3.pptx

Checking the test file

In [97]:
test_report = Report(_test_report_pptx)
print(test_report)

Report HESTO-202612_Report_24-HTIDS24_Smith-rev3.pptx (33 slides)
Project ID: 24-HTIDS24-0009, PI: Jane Smith

Category    Prior    Current
----------  -------  -------
overall     Y        Y
cost        Y        Y
schedule    G        G
technical   G        G
staffing    G        G
facilities  G        G

Accommodation:
Category                          Sub-category  Value
--------------------------------  ----------  --------------
payload size                      length      10.0
                                  width       10.0
                                  height      10.0
payload volume                                1.0
power requirements                average     5.0
                                  peak        10.0
mass                                          5.4
pointing requirements             arcsecs     60.0
                                  arcminutes  1.0
data rate                         average     15.0
                                  peak        100.0
power interface port                          db-9, 28 v, 1a
communication interface protocol              uart
data communication port                       db-9
requires thermal isolation                    false
special power considerations                  none

Publications:
      Type choose one of below                                                   Title Publication/Presentation Date Publisher/Conference Name                                           URL
Conference presentation (oral) Development of the Next-Generation Solar X-ray detector                   23-Jan-2026              IEEE NSS/MIC https://ieeexplore.ieee.org/document/10657175

In [98]:
test_report.accomodation_table

                            category sub_category           value
0                       payload size       length            10.0
1                       payload size        width            10.0
2                       payload size       height            10.0
3                     payload volume                          1.0
4                 power requirements      average             5.0
5                 power requirements         peak            10.0
6                               mass                          5.4
7              pointing requirements      arcsecs            60.0
8              pointing requirements   arcminutes             1.0
9                          data rate      average            15.0
10                         data rate         peak           100.0
11              power interface port               db-9, 28 v, 1a
12  communication interface protocol                         uart
13           data communication port                         db-9
14        requires thermal isolation                        false
15      special power considerations                         none

In [99]:
test_report.publication_table

,Type choose one of below,Title,Publication/Presentation Date,Publisher/Conference Name,URL
0,Conference presentation (oral),Development of the Next-Generation Solar X-ray...,23-Jan-2026,IEEE NSS/MIC,https://ieeexplore.ieee.org/document/10657175

In [100]:
test_report.patents_table

,"Type (Issued, Filing)",Name,Patent or License Number,Date,"Resource Link (e.g., Google Patents Link)"
0,Issued,Art of transmitting electrical energy through ...,US787412A,1900-05-16,https://patents.google.com/patent/US787412A/

In [101]:
test_report.student_metrics_table

,Student Name (first last),Major,"Affiliation (School, University, etc.)","Level (High School, Undergrad, Grad, PhD)"
0,John Doe,Physics,University of Alabama,Undergrad

In [103]:
files = [
    find_latest_report_pptx(Path("C:\\Users\\shoffma5\\Box\\HESTO\\HTIDeS")),
    find_latest_report_pptx(Path("C:\\Users\\shoffma5\\Box\\HESTO\\HFOS")),
    find_latest_report_pptx(Path("C:\\Users\\shoffma5\\Box\\HESTO\\Special Projects"))
]
files = pd.concat(files, ignore_index=True)
print(f"Found {len(files)} report files:")
files.to_csv("report_files.csv", index=False)
files

Found 78 report files:

,file_path,project_id,report_date,year,principal_investigator,modified,folder
0,C:\Users\shoffma5\Box\HESTO\HTIDeS\24-HTIDS\24...,24-HTIDS24-0022,202605,2024,Lindsay Glesener,2026-06-10 10:51:52,C:\Users\shoffma5\Box\HESTO\HTIDeS\24-HTIDS\24...
1,C:\Users\shoffma5\Box\HESTO\HTIDeS\24-HTIDS\24...,24-HTIDS24-0036,202604,2024,Maria Usanova,2026-04-24 16:39:00,C:\Users\shoffma5\Box\HESTO\HTIDeS\24-HTIDS\24...
2,C:\Users\shoffma5\Box\HESTO\HTIDeS\24-HTIDS\24...,24-HTIDS24-0025,202604,2024,Gregory Miller,2026-04-26 16:14:23,C:\Users\shoffma5\Box\HESTO\HTIDeS\24-HTIDS\24...
3,C:\Users\shoffma5\Box\HESTO\HTIDeS\24-HTIDS\24...,24-HTIDS24-0006,202604,2024,Shawn Liang,2026-04-29 11:58:54,C:\Users\shoffma5\Box\HESTO\HTIDeS\24-HTIDS\24...
4,C:\Users\shoffma5\Box\HESTO\HTIDeS\24-HTIDS\24...,24-HTIDS24-0003,202601,2024,Jan Egedal,2026-04-30 17:03:16,C:\Users\shoffma5\Box\HESTO\HTIDeS\24-HTIDS\24...
...,...,...,...,...,...,...,...
73,C:\Users\shoffma5\Box\HESTO\HFOS\20-HFOS\20-HF...,20-HFOS20-0011,202604,2020,Wendy Frank,2026-05-05 10:15:40,C:\Users\shoffma5\Box\HESTO\HFOS\20-HFOS\20-HF...
74,C:\Users\shoffma5\Box\HESTO\Special Projects\2...,SPICES,202304,2020,Sue Lepri,2023-04-27 10:10:25,C:\Users\shoffma5\Box\HESTO\Special Projects\2...
75,C:\Users\shoffma5\Box\HESTO\Special Projects\2...,MAGIC,202605,2020,David Miles,2026-05-10 08:29:53,C:\Users\shoffma5\Box\HESTO\Special Projects\2...
76,C:\Users\shoffma5\Box\HESTO\Special Projects\2...,Lindsay,,2020,Glesener,2023-09-07 11:33:16,C:\Users\shoffma5\Box\HESTO\Special Projects\2...
77,C:\Users\shoffma5\Box\HESTO\Special Projects\1...,CHIMERA,202605,2018,David Miles,2026-05-10 08:55:00,C:\Users\shoffma5\Box\HESTO\Special Projects\1...

In [ ]:
files[files['year'] == 2024]

,file_path,project_id,report_date,year,principal_investigator,modified,folder
filename,,,,,,,
HESTO-202605_TriannualReport_23-HTIDS24-0022_PI-Glesener-rev4.pptx,C:\Users\shoffma5\Box\HESTO\HTIDeS\24-HTIDS\24...,24-HTIDS24-0022,202605,2024,Lindsay Glesener,2026-06-10 10:51:52,C:\Users\shoffma5\Box\HESTO\HTIDeS\24-HTIDS\24...
HESTO-202604_Report_24-HTIDS-0036_Usanova-rev3.pptx,C:\Users\shoffma5\Box\HESTO\HTIDeS\24-HTIDS\24...,24-HTIDS24-0036,202604,2024,Maria Usanova,2026-04-24 16:39:00,C:\Users\shoffma5\Box\HESTO\HTIDeS\24-HTIDS\24...
HESTO-202604_Report_24-HTIDS24-0025_Miller-rev3_Apr26_2026.pptx,C:\Users\shoffma5\Box\HESTO\HTIDeS\24-HTIDS\24...,24-HTIDS24-0025,202604,2024,Gregory Miller,2026-04-26 16:14:23,C:\Users\shoffma5\Box\HESTO\HTIDeS\24-HTIDS\24...
HESTO-202604_Report_HTIDS24-0006_Liang.pptx,C:\Users\shoffma5\Box\HESTO\HTIDeS\24-HTIDS\24...,24-HTIDS24-0006,202604,2024,Shawn Liang,2026-04-29 11:58:54,C:\Users\shoffma5\Box\HESTO\HTIDeS\24-HTIDS\24...
HESTO-202601_TriannualReport_24-HTIDS24-0003_Egedal-May.pptx,C:\Users\shoffma5\Box\HESTO\HTIDeS\24-HTIDS\24...,24-HTIDS24-0003,202601,2024,Jan Egedal,2026-04-30 17:03:16,C:\Users\shoffma5\Box\HESTO\HTIDeS\24-HTIDS\24...
HESTO-202605_Report_24-HTIDS24-0039_Kataria-rev3-v2.pptx,C:\Users\shoffma5\Box\HESTO\HTIDeS\24-HTIDS\24...,24-HTIDS24-0039,202605,2024,Dhirendra Kataria,2026-06-09 15:58:16,C:\Users\shoffma5\Box\HESTO\HTIDeS\24-HTIDS\24...
HESTO-202605_Report_Proposal0005_deNolfo_v1.pptx,C:\Users\shoffma5\Box\HESTO\HTIDeS\24-HTIDS\24...,24-HTIDS24-0005,202605,2024,Georgia de Nolfo,2026-04-26 13:47:32,C:\Users\shoffma5\Box\HESTO\HTIDeS\24-HTIDS\24...

In [ ]:
test_file = files[files['year'] == 2024].iloc[0]['file_path']

In [ ]:
this_report = Report(test_file)

HESTO-202605_TriannualReport_23-HTIDS24-0022_PI-Glesener-rev4.pptx: unrecognised publication type 'Peer-reviewed journal'. Expected one of: ['Peer-reviewed publication', 'Non-Peer-reviewed publication', 'Conference presentation (oral)', 'Conference presentation (poster)', 'Web article']
HESTO-202605_TriannualReport_23-HTIDS24-0022_PI-Glesener-rev4.pptx: unrecognised publication type 'Non-peer-reviewed journal'. Expected one of: ['Peer-reviewed publication', 'Non-Peer-reviewed publication', 'Conference presentation (oral)', 'Conference presentation (poster)', 'Web article']

In [ ]:
this_report

Report HESTO-202605_TriannualReport_23-HTIDS24-0022_PI-Glesener-rev4.pptx (35 slides)
Project ID: 24-HTIDS24-0022, PI: Lindsay Glesener

Accommodation:
Category                          Sub-category  Value
--------------------------------  ----------  -------------------------------
payload size                      length      10.0
                                  width       10.0
                                  height      20.0
payload volume                                2u
power requirements                            approx. 10 w average
mass                                          tbd
pointing requirements             arcsecs     ~1 deg abs. knowledge
                                  arcminutes  sun-pointed.
data rate                                     peak 128 mbps
power interface port                          d-sub 9-pin connector (tbr).
communication interface protocol              uart (rs-422) or ethernet, tbd.
data communication port                       db-9 (tbr).
requires thermal isolation                    false
special power considerations                  tbd

Publications:
        Type choose one of below Title Publication/Presentation Date Publisher/Conference Name URL
           Peer-reviewed journal
       Non-peer-reviewed journal
  Conference presentation (oral)
Conference presentation (poster)
                     Web article

In [ ]:
this_report.accomodation_table

,category,sub_category,value
0,payload size,length,10.0
1,payload size,width,10.0
2,payload size,height,20.0
3,payload volume,,2u
4,power requirements,,approx. 10 w average
5,mass,,tbd
6,pointing requirements,arcsecs,~1 deg abs. knowledge
7,pointing requirements,arcminutes,sun-pointed.
8,data rate,,peak 128 mbps
9,power interface port,,d-sub 9-pin connector (tbr).
10,communication interface protocol,,"uart (rs-422) or ethernet, tbd."
11,data communication port,,db-9 (tbr).
12,requires thermal isolation,,false
13,special power considerations,,tbd

In [ ]:
this_report.publication_table

,Type choose one of below,Title,Publication/Presentation Date,Publisher/Conference Name,URL
0,Peer-reviewed journal,,,,
1,Non-peer-reviewed journal,,,,
2,Conference presentation (oral),,,,
3,Conference presentation (poster),,,,
4,Web article,,,,

In [ ]:
this_report.project_status

In [ ]:
this_report.patents_table

In [ ]:
test_file = files[files['year'] == 2024].iloc[1]['file_path']
test_file

WindowsPath('C:/Users/shoffma5/Box/HESTO/HTIDeS/24-HTIDS/24-HTIDS24-0036 Maria Usanova/Reports/HESTO/HESTO-202604_Report_24-HTIDS-0036_Usanova-rev3.pptx')

In [ ]:
this_report = Report(test_file)

HESTO-202604_Report_24-HTIDS-0036_Usanova-rev3.pptx: status category 'cost' has invalid prior value 'n/a'. Expected one of: ['g', 'y', 'r', 'green', 'yellow', 'red']
HESTO-202604_Report_24-HTIDS-0036_Usanova-rev3.pptx: status category 'schedule' has invalid prior value 'n/a'. Expected one of: ['g', 'y', 'r', 'green', 'yellow', 'red']
HESTO-202604_Report_24-HTIDS-0036_Usanova-rev3.pptx: status category 'technical' has invalid prior value 'n/a'. Expected one of: ['g', 'y', 'r', 'green', 'yellow', 'red']
HESTO-202604_Report_24-HTIDS-0036_Usanova-rev3.pptx: status category 'staffing' has invalid prior value 'n/a'. Expected one of: ['g', 'y', 'r', 'green', 'yellow', 'red']
HESTO-202604_Report_24-HTIDS-0036_Usanova-rev3.pptx: status category 'facilities' has invalid prior value 'n/a'. Expected one of: ['g', 'y', 'r', 'green', 'yellow', 'red']
HESTO-202604_Report_24-HTIDS-0036_Usanova-rev3.pptx: status category 'overall' has invalid prior value 'n/a'. Expected one of: ['g', 'y', 'r', 'green', 'yellow', 'red']
HESTO-202604_Report_24-HTIDS-0036_Usanova-rev3.pptx: unrecognised publication type 'Peer-reviewed journal'. Expected one of: ['Peer-reviewed publication', 'Non-Peer-reviewed publication', 'Conference presentation (oral)', 'Conference presentation (poster)', 'Web article']
HESTO-202604_Report_24-HTIDS-0036_Usanova-rev3.pptx: unrecognised publication type 'Non-peer-reviewed journal'. Expected one of: ['Peer-reviewed publication', 'Non-Peer-reviewed publication', 'Conference presentation (oral)', 'Conference presentation (poster)', 'Web article']

In [ ]:
this_report.accomodation_table

                            category sub_category value
0                       payload size       length   6.0
1                       payload size        width   6.0
2                       payload size       height   6.0
3                     payload volume                1.0
4                 power requirements                1.0
5                               mass                tbd
6              pointing requirements                tbd
7                          data rate                tbd
8               power interface port                tbd
9   communication interface protocol                tbd
10           data communication port                tbd
11        requires thermal isolation               true
12      special power considerations               none

In [ ]:
this_report.summary

{'date': '04/04/2026',
 'proposal title': 'A Magnetometer Based on Magneto-Optical Effects for Space Applications',
 'technology name (acronym)': 'MiniMag',
 'principal investigator': 'Maria Usanova',
 'pi email': 'Maria.Usanova@lasp.colorado.edu',
 'affiliation': 'University of Colorado Boulder',
 'proposal id': '24-HTIDS24-0036',
 'research regime': 'Magnetosphere',
 'hesto taxonomy': 'TX08.3.1 Field and Particle Detectors',
 'instrument type(s)': 'Magnetometer',
 'technology keyword': 'N/A',
 'project summary (two to three sentences)': 'Advance MiniMag from TRL 2-3 to TRL 6 by optimizing a sensor and developing a compact, low-SWaP magnetometer. The effort targets improved sensitivity and measurements from DC to 40 kHz, culminating in demonstration of a 1-axis instrument in a relevant environment.',
 'techport url': 'TBD'}